Change: scope app styling with css baseline container
foxglove/studio pull request #1590
Opened 2021-08-03 22:43 UTC by defunctzombie

**User-Facing Changes**
None

**Description**
Rather than setting styles globally on elements, scope styling
to a top level app container. The CssBaseline component should be
used as this top level app container.

2021-08-03 23:27 UTC, 2metres requested changes
The typography is currently broken in chromatic and the background is now included

2021-08-03 23:27 UTC, 2metres commented on desktop/renderer/index.tsx
> +
We should probably consider name spacing our root selector something like `#foxglove-root`

2021-08-03 23:31 UTC, defunctzombie commented on desktop/renderer/index.tsx
> +
Any benefit to this since we don't reference it in studio-base?

2021-08-04 23:32 UTC, defunctzombie commented
TextContent has a line height of 1.65 - this causes too much space between lines.

2021-08-05 20:22 UTC, merged