Specify in metrics when player was initialized with the demo bag
foxglove/studio pull request #2237
Opened 2021-12-01 18:58 UTC by esthersweon

**User-Facing Changes**
- None

**Description**
- Differentiate between players being initialized with demo bag vs. user data

2021-12-01 19:04 UTC, jhurliman requested changes

2021-12-01 19:04 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveDataPlatformPlayer/index.ts
> +    this._metricsCollector.initialized({ isDemoBag: false });
Having to set this to false everywhere feels like it is leaking a detail of one part of the app (the fact that we have a demo bag) to all data sources. Can this be made optional (and defaulted to false), so only the actual demo bag playback sets `isDemoBag: true`?

2021-12-01 19:04 UTC, jhurliman commented on packages/studio-base/src/util/isDemoBagUrl.ts
> +const DEMO_BAG_URL = "https://storage.googleapis.com/foxglove-public-assets/demo.bag";
This isn't exported so I assume we are defining this URL in two places in the app now. Can it be exported once and imported here?

2021-12-01 19:06 UTC, jhurliman requested changes

2021-12-01 19:06 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveDataPlatformPlayer/index.ts
> +    this._metricsCollector.initialized({ isDemoBag: false });
I don't think this is the correct place to call `initialized`. PLAYER_CONSTRUCTED conveys when the data source constructor is called. PLAYER_INITIALIZED, in other players, happens when a connection is successfully established.

2021-12-01 19:23 UTC, esthersweon commented on packages/studio-base/src/players/FoxgloveDataPlatformPlayer/index.ts
> +    this._metricsCollector.initialized({ isDemoBag: false });
Moved to past `this._initialized = {  preloadedMessages: ... }` later in this file.

2021-12-01 19:28 UTC, esthersweon commented on packages/studio-base/src/util/isDemoBagUrl.ts
> +const DEMO_BAG_URL = "https://storage.googleapis.com/foxglove-public-assets/demo.bag";
There's currently a `DEMO_BAG_URL` in both the desktop and web root.

2021-12-03 02:18 UTC, merged

2021-12-15 01:06 UTC, defunctzombie commented
Looking back at this and I'm generally not a fan of how this hard-coded the plumbing for demo url detection. We should be passing properties to constructors if we want to influence actions like this rather than adding custom handling for constants in the player.