Improve usability for Diagnostic Detail panel
foxglove/studio pull request #2684
Opened 2022-01-15 23:22 UTC by defunctzombie

**User-Facing Changes**
TBD

**Description**
The autocomplete in the Diagnostic Detail panel would hide available options once the user selected one. To change to a different diagnostic the user has to click the input, realize they can delete their text, delete all the text and type again to find their entry.

This change switches the autocomplete input to the mui Autocomplete component. This component exhibits better UX behavior. When focusing on the input, the user is shown all available entries with their current entry highlighted. This also resolves some glitches with the dropdown.

This change also modifies the autocomplete options logic to ignore empty hardware ids with no name from showing in the autocomplete options list. These entries would create blanks in the dropdown list.

Fixes: #2379

2022-01-15 23:24 UTC, defunctzombie commented
@jhurliman can you give this PR a spin and see how it feels to use especially for the issues raised in #2379 . Once we are happy with the interactions we can get feedback from others on our changes.

2022-01-18 20:51 UTC, jhurliman commented
@defunctzombie yes, this is better. Ship it

2022-01-19 04:25 UTC, jhurliman requested changes
I think the stories `"DiagnosticStatusPanel:Selected Hardware ID Only"`, `"DiagnosticStatusPanel:Selected Name"`, and `"DiagnosticStatusPanel:Moved Divider"` should be updated. It sets the `name` field to values such as `hardware_id1: name1` which we assume is a Cruise-ism, so the output looks off with the redundant hardware ids.

Another thing that appears to have changed is the dropdown is always visible, even when there are zero or one hardware ids. I prefer the previous behavior of hiding the dropdown in those cases (I generally lean toward minimal UI for Studio panels), but it's a good discussion point.

2022-01-19 16:18 UTC, defunctzombie commented
> I think the stories `"DiagnosticStatusPanel:Selected Hardware ID Only"`, `"DiagnosticStatusPanel:Selected Name"`, and `"DiagnosticStatusPanel:Moved Divider"` should be updated. It sets the `name` field to values such as `hardware_id1: name1` which we assume is a Cruise-ism, so the output looks off with the redundant hardware ids.

I looked at this and it's actually not because the story sets the name field to `hardware_id1: name1` but because the `<DiagnosticStatus>` component which renders each DiagnosticInfo item renders the displayName field from each item. We could detect that you've filtered down to a specific hardware_id or even a hardware_id and name and pass a prop to the DiagnositcStatus component to avoid showing the heading but its starting to feel like a bit too much scope creep for me on this specific fix.

> Another thing that appears to have changed is the dropdown is always visible, even when there are zero or one hardware ids. I prefer the previous behavior of hiding the dropdown in those cases (I generally lean toward minimal UI for Studio panels), but it's a good discussion point.

What if there are multiple names under a single hardware id? It would be weird UX to me for the panel to automatically select a diagnostic when you open a datasource just because that happened to be the first message seen in the data source. I actually find this behavior for the image panel somewhat annoying and another one of those areas where the app is trying to be too clever instead of making it easy and obvious how to configure the panel with your data.

2022-01-19 22:30 UTC, defunctzombie commented
@jhurliman I had accidentally removed a floating from the panel toolbar when I was iterating. I've put that back.

2022-01-19 22:55 UTC, jtbandes commented
This text should probably be disabled (grayed out), or just hide the dropdown when waiting for diagnostics because we already say it in the center of the panel:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/14237/150231152-f6cb070c-c84a-46e0-b68c-11c38e5bbd21.png">

We also need a drop shadow on the menu so it doesn't blend in with other UI elements:
<img width="269" alt="image" src="https://user-images.githubusercontent.com/14237/150231262-25be27a0-d40b-45b8-9a75-59aa05a7a1de.png">

compare with the Message Path Input autocomplete which has a shadow:
<img width="335" alt="image" src="https://user-images.githubusercontent.com/14237/150231250-3082cf76-0c77-4e79-ac86-c1ed897b4e34.png">

2022-01-19 22:56 UTC, jhurliman approved these changes

2022-01-19 23:01 UTC, jtbandes requested changes
needs UI cleanup

2022-01-20 04:49 UTC, defunctzombie commented
I've updated the PR to disable the dropdown when there are no diagnostics - this prevents "waiting for diagnostics..." from being shown in the empty state.

I've updated the PR to set the default paper elevation to `2` which brings back a dropshadow.

@2metres Thoughts on why the default paper elevation was set to 0?

2022-01-20 04:49 UTC, defunctzombie commented on packages/studio-base/src/theme/muiComponents.ts
> +        elevation: 2,
@2metres is this ok to do here?

2022-01-20 05:13 UTC, 2metres commented on packages/studio-base/src/theme/muiComponents.ts
> +        elevation: 2,
Yep looks good to me.

2022-01-20 14:35 UTC, defunctzombie commented
@jtbandes take a look and if you are 👍 on the changes please squash and merge.

2022-01-20 17:53 UTC, jtbandes approved these changes

2022-01-20 17:53 UTC, merged