Replace fluentui mergeStyleSets, mergeStyles and makeStyles to MUI makeStyles
foxglove/studio pull request #2802
Opened 2022-02-08 03:59 UTC by 2metres

**User-Facing Changes**
Draft PR for visual diff

**Description**

2022-02-09 17:12 UTC, jtbandes commented on packages/studio-base/src/components/ErrorDisplay.tsx
> +import { createStyles, makeStyles } from "@mui/styles";
What's the purpose of this?

> This function doesn't really "do anything" at runtime, it's just the identity function. Its only purpose is to defeat TypeScript's type widening when providing style rules to makeStyles/withStyles which are a function of the Theme.

Seems like it should only be added when there are type errors?

2022-02-09 17:26 UTC, jtbandes requested changes
Looks like some contrast got worse (at least in light mode) on 3D view button:

<img width="1345" alt="image" src="https://user-images.githubusercontent.com/14237/153255783-cb959eaa-fdd1-4640-b27b-25e1d5881240.png">


This one seems like a real problem since the notification dot went away:

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/14237/153255906-bf28bcc7-3bf9-454e-a105-834a85f411ac.png">

2022-02-09 17:26 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDimensionalViz/DebugStats.tsx
> +// import { makeStyles } from "@fluentui/react";
leftover

2022-02-09 17:26 UTC, jtbandes commented on packages/studio-base/src/typings/fluentui.d.ts
> +// TODO: Move this into a mui.d.ts file
move before merging?

2022-02-15 01:36 UTC, 2metres commented on packages/studio-base/src/panels/diagnostics/DiagnosticStatus.tsx
> +        backgroundColor: theme.palette.grey[50],
The idea with `grey` (at least IMO) is that is a consistent decay of neutral colors across themes, not nessicarily consistent like `common.white/black`

2022-02-15 01:40 UTC, 2metres commented on packages/studio-base/src/typings/fluentui.d.ts
> +// TODO: Move this into a mui.d.ts file
What is the purpose of this? From what I can tell in the `makeStyles` usage it's not working.

2022-02-15 01:41 UTC, 2metres commented on packages/studio-base/src/typings/fluentui.d.ts
> +// TODO: Move this into a mui.d.ts file
I've copied it from here: https://mui.com/guides/migration-v4/#heading-mui-styles

2022-02-15 01:53 UTC, 2metres commented on packages/studio-base/src/panels/diagnostics/DiagnosticStatus.tsx
> +        backgroundColor: theme.palette.grey[50],
I managed to get the badge back there are some subtle differences between MUI and Fluent makeStyles mainly around psuedo and nested selectors.

```diff
const useStyles = makeStyles({
  root: {
-    ":hover": {
+    "&:hover": {
     }
-   ".child-selector": {
+   "& .child-selector": {
    }
  }
})
```

2022-02-15 01:53 UTC, 2metres commented on packages/studio-base/src/panels/diagnostics/DiagnosticStatus.tsx
> +        backgroundColor: theme.palette.grey[50],
@jtbandes I can't see the contrast difference you're referrring to, can you provide a bit more detail?

2022-02-16 22:00 UTC, defunctzombie approved these changes

2022-02-16 22:12 UTC, jtbandes approved these changes

2022-02-16 22:12 UTC, jtbandes commented on packages/studio-base/src/typings/mui.d.ts
> +declare module "@mui/styles/defaultTheme" {
maybe drop a comment with link to documentation on what this is for? It seems odd to me that we would import something from mui, and modify something from mui to re-export the thing that was already from mui... With the other theme libraries (styled-components) we've done overrides like this when we wanted to inject our custom theme object that the library was not already aware of. But maybe this is normal in mui?

2022-02-16 22:39 UTC, 2metres commented on packages/studio-base/src/typings/mui.d.ts
> +declare module "@mui/styles/defaultTheme" {
Just dove into this with @defunctzombie I don't think it really does anything. Removing for now.

2022-02-16 22:46 UTC, merged