Move data source info into Data Source Sidebar
foxglove/studio pull request #3060
Opened 2022-03-22 21:17 UTC by 2metres

**User-Facing Changes**
Move data source info into Data Source Sidebar once connection is live.

**Description**

2022-03-25 01:08 UTC, jtbandes commented
Sidebar is scrollable even when the list of topics is short:

https://user-images.githubusercontent.com/14237/160035069-ae47189f-7879-455e-ba15-bda2681110f1.mov

2022-03-25 01:09 UTC, jtbandes commented
Consider adding a tooltip to the "copy to clipboard" button telling me what it's going to copy. I wasn't sure whether to expect the datatype or the topic name to be copied. In hindsight it's definitely more useful to copy the topic name, but the button is centered so that wasn't obvious.

<img width="63" alt="image" src="https://user-images.githubusercontent.com/14237/160035114-e3e64091-3b88-4cbc-b5e4-9e224c80a252.png">

2022-03-25 01:10 UTC, jtbandes commented
Search behavior is a bit weird — am I searching across the concatenation of topic+datatype?

<img width="268" alt="image" src="https://user-images.githubusercontent.com/14237/160035226-80d2eaf7-b5d2-493e-a3a3-f9c1ed5cb47a.png">
<img width="297" alt="image" src="https://user-images.githubusercontent.com/14237/160035238-86e9c1c0-12d7-4224-8a6a-108a50ba8753.png">

2022-03-25 01:11 UTC, jtbandes commented
Sidebar jumps around as I type in the search field:

https://user-images.githubusercontent.com/14237/160035304-cf1f920d-4259-43c1-af46-76444bc103a2.mov

2022-03-25 01:13 UTC, jtbandes commented
Search field appearance is inconsistent with other search fields in the app:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/14237/160035433-5fae5341-442c-4ebc-870c-d8227090ce35.png">
<img width="244" alt="image" src="https://user-images.githubusercontent.com/14237/160035437-4f78864f-e28f-4cbf-beb3-159bacedb176.png">

2022-03-25 01:14 UTC, jtbandes commented on packages/studio-base/src/components/DataSourceSidebar/ProblemsList.tsx
> +          No problems found
I think "no problems found" is a strange phrase since I didn't really come to the sidebar _looking_ for problems (unless I already knew there was one).

What do you think of completely hiding the Problems tab if there are no problems?

2022-03-25 01:17 UTC, jtbandes commented
Alignment of problems text, badge, and underline feels off:

<img width="119" alt="image" src="https://user-images.githubusercontent.com/14237/160035726-a16e8e8d-45b1-4bf8-b666-01c665cb58c2.png">

Tab underline appearance is also inconsistent with other tabbed UIs in the app:

<img width="231" alt="image" src="https://user-images.githubusercontent.com/14237/160035795-a3823845-55d5-4f66-b596-89c71cc175c2.png">


Long error messages make the sidebar scroll horizontally:

https://user-images.githubusercontent.com/14237/160035696-3d651084-8503-4bf8-84e6-bb94970a7053.mov

2022-03-25 01:19 UTC, jtbandes commented
Spinner spins off-center:

https://user-images.githubusercontent.com/14237/160036042-a70d8427-516e-4913-9386-6ea51b79cc27.mov

2022-03-25 01:28 UTC, jtbandes requested changes

2022-03-25 01:28 UTC, jtbandes commented on packages/studio-base/src/components/CssBaseline.tsx
> +        height: 4,
just curious, did this have an effect? I'd think it would be px by default.

2022-03-25 01:28 UTC, jtbandes commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +  "@media (pointer: fine)": {
What's this for?

2022-03-25 01:28 UTC, jtbandes commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +    playerPresence === PlayerPresence.RECONNECTING
We should think carefully about including "reconnecting" ... when I test with a WebSocket server (`npx @foxglove/ws-protocol-examples@latest sysmon`), if I stop the server, it goes back to the "Skeleton" state. In some ways this makes sense, but in some ways it's annoying because the UI now has this "shimmer" animation that makes it feel like an active loading state, while in reality it's never going to load until I start my server again.

<img width="370" alt="image" src="https://user-images.githubusercontent.com/14237/160036468-051e38c1-d5a6-4879-acf7-6af477480d87.png">

Also the skeletons seem to move when I move my mouse over them:

https://user-images.githubusercontent.com/14237/160036573-a4d535ec-fd88-4248-b001-5c178a7f9650.mov

2022-03-25 01:28 UTC, jtbandes commented on packages/studio-base/src/components/SidebarContent.tsx
> +      <ContentWrapper {...{ disablePadding }}>{children}</ContentWrapper>
A little less duplication is not worth it here IMO
```suggestion
      <ContentWrapper disablePadding={disablePadding}>{children}</ContentWrapper>
```

2022-03-25 01:42 UTC, jtbandes commented
Maybe not something to tackle now...but we should probably remove "end time" and "duration" for live connections. Or at least rename "end time" to "current time"? Might need to add some `isLive` boolean to the players since I'm not sure we know that information otherwise.

<img width="297" alt="image" src="https://user-images.githubusercontent.com/14237/160037855-c61f1c24-0bc6-4df6-b76d-83fdd4b84afa.png">

2022-03-28 22:47 UTC, 2metres commented
> Maybe not something to tackle now...but we should probably remove "end time" and "duration" for live connections. Or at least rename "end time" to "current time"? Might need to add some `isLive` boolean to the players since I'm not sure we know that information otherwise.

I've thought about this a few times opening an issue for further discussion: https://github.com/foxglove/studio/issues/3085

2022-03-28 22:49 UTC, 2metres commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +    playerPresence === PlayerPresence.RECONNECTING
![](https://media1.giphy.com/media/YwAgyCddum3K0/giphy.gif?cid=ecf05e47km39hjijs7wpn9zill0v2pa4n22kss18a560t5g5)

2022-03-28 22:51 UTC, 2metres commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +  "@media (pointer: fine)": {
This is me trying to acknoledge the fact that hide/show on hover is bad for touch devices so by putting `pointer: fine` the hover interaction only appears on devices with "fine" cursors.

2022-03-28 22:51 UTC, 2metres commented on packages/studio-base/src/components/CssBaseline.tsx
> +        height: 4,
Yeah this should be no change just came across it in my travels

2022-03-28 22:52 UTC, 2metres commented on packages/studio-base/src/components/DataSourceSidebar/ProblemsList.tsx
> +          No problems found
Maybe just this instead? ![image](https://user-images.githubusercontent.com/924528/160499973-5084e28c-80ed-444d-96cd-d6740cfda8c9.png)

2022-03-28 23:13 UTC, jtbandes approved these changes
Discussed via huddle, all concerns were either addressed or deemed not important enough to block.

2022-03-29 00:58 UTC, amacneil commented
since it's a pretty big change, can we do a live review of this before merging? either tomorrow after team planning, or Wednesday (PT)

2022-03-30 20:12 UTC, amacneil commented
follow up items
- start/end time should be hidden when connected to live data source (separate ticket?)
- weird little square in bottom right
- can we auto-select the problems tab when problems appear?

2022-03-30 21:41 UTC, esthersweon commented
Still think we could save more space by having one "Time" heading that has a `startTime - endTime (duration)` that intelligently removes duplicate info.

e.g. the below could be displayed as 
```
TIME
2018-07-23 8:28:47.647 - 8:29:06.797 PM PDT (19.1 sec)
```
instead.

<img width="320" alt="Screen Shot 2022-03-30 at 2 39 37 PM" src="https://user-images.githubusercontent.com/6993359/160935527-f4542be6-f513-4e54-a933-74e6a89cba23.png">

2022-03-31 03:26 UTC, merged