Don't use header.stamp time to expire point markers
foxglove/studio pull request #3314
Opened 2022-05-04 20:29 UTC by foxymiles

**User-Facing Changes**
This fixes an issue with the display of point cloud messages in the 3d panel when a delay time is set.

**Description**
We were using the message's `header.stamp` time to determine the expiration time of the point cloud message. We should use the messages `receiveTime` in this case.

Fixes #3283

2022-05-04 20:34 UTC, jtbandes commented
Contradicts https://github.com/foxglove/studio/pull/2986

2022-05-04 20:40 UTC, foxymiles commented
> Contradicts #2986

See slack thread

2022-05-04 20:42 UTC, jtbandes commented
Slack threads are not publicly viewable and not persistent. Can you screenshot or summarize the relevant discussion here so that a future (or present) reader knows why this change is being made? The PR description currently explains what is changing, but not really _why_.

2022-05-05 01:09 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDimensionalViz/SceneBuilder/MessageCollector.ts
> -        (marker.message as { header?: { stamp?: Time } }).header?.stamp ?? marker.receiveTime;
Doesn't this apply the change to all displayable objects and not just point clouds? Was that intentional?

2022-05-05 11:45 UTC, foxymiles commented on packages/studio-base/src/panels/ThreeDimensionalViz/SceneBuilder/MessageCollector.ts
> -        (marker.message as { header?: { stamp?: Time } }).header?.stamp ?? marker.receiveTime;
@jhurliman Said we should just revert this change from #2986 so yeah it's my understanding that this is the intention.

2022-05-05 14:25 UTC, foxymiles commented on packages/studio-base/src/panels/ThreeDimensionalViz/SceneBuilder/MessageCollector.ts
> -        (marker.message as { header?: { stamp?: Time } }).header?.stamp ?? marker.receiveTime;
This was our old behavior:

```typescript
  isExpired(currentTime: Time) {
    if (this.lifetime == undefined) {
      // Do not expire markers if we can't tell what their lifetime is.
      // They'll be flushed later if needed (see flush below)
      return false;
    }
    const lifetime: Time = this.lifetime;

    if (areEqual(lifetime, ZERO_TIME)) {
      // Do not expire markers with infinite lifetime (lifetime == 0)
      return false;
    }

    // we use the receive time (clock) instead of the header stamp
    // to match the behavior of rviz
    const expiresAt = add(this.receiveTime, lifetime);

    return isGreaterThan(currentTime, expiresAt);
  }
```

2022-05-09 17:16 UTC, jhurliman requested changes
This isn't correct, it mixes the `receiveTime` and `header.stamp` time sources for some renderables.

2022-05-09 17:20 UTC, closed without merging