Improve settings grid layout
foxglove/studio pull request #3349
Opened 2022-05-11 14:11 UTC by foxymiles

**User-Facing Changes**
None

**Description**
This improves the settings field grid layout by putting all elements in a common parent grid and capping the width of the input fields.

https://user-images.githubusercontent.com/93935560/167870240-50f6db27-39b9-454d-b9a5-25f49282c84e.mov

2022-05-11 23:06 UTC, 2metres requested changes

2022-05-11 23:06 UTC, 2metres commented on packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
>    const paddingLeft = theme.spacing(2 + 2 * Math.max(0, indent - 1));
The Stack component has a `paddingLeft` prop that is tapped into the `theme.spacing`.

```suggestion
  const paddingLeft = 2 + 2 * Math.max(0, indent - 1);
```

2022-05-11 23:06 UTC, 2metres commented on packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
> +      <Stack direction="row" alignItems="center" style={{ ...style, paddingLeft }} fullHeight>
The Stack component has a paddingLeft prop that is tapped into the theme.spacing.

```suggestion
      <Stack direction="row" alignItems="center" style={style} paddingLeft={paddingLeft} fullHeight>
```

2022-05-11 23:06 UTC, 2metres commented on packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
> +  style,
Do we have to pass the `style` prop through here?

2022-05-12 14:01 UTC, foxymiles commented on packages/studio-base/src/components/SettingsTreeEditor/FieldEditor.tsx
> +  style,
Yeah in order to get the last-time bottom padding.

2022-05-13 14:52 UTC, foxymiles commented on packages/studio-base/src/components/SettingsTreeEditor/NodeEditor.tsx
> +      {indent === 1 && <Divider style={{ gridColumn: "span 2" }} />}
I agree beyond more than a few attributes inline styles get harder to read but for a single attribute it doesn't seem like it's worth going through the extra boilerplate and losing the locality of code reference. What do you think?

2022-05-16 21:51 UTC, 2metres approved these changes

2022-05-16 21:51 UTC, 2metres commented on packages/studio-base/src/components/SettingsTreeEditor/index.tsx
> +  gridTemplateColumns: "minmax(4rem, 1fr) minmax(min-content, 14rem)",
```suggestion
  gridTemplateColumns: "minmax(4rem, 1fr) minmax(min-content, 12rem)",
```

2022-05-17 11:51 UTC, merged