[New3D] Go faster
foxglove/studio pull request #3773
Opened 2022-07-02 02:26 UTC by jhurliman

WIP

- Fix followTf in settings sidebar
- Enable frustum culling for LaserScan
- Dispose geometry when disabling PointCloud or LaserScan topic
- Topic error when we are not rendering in the user's desired frame
- Add caching for _updateMaterials()
- Performance optimizations for TransformTree, remove AVL usage, trim by count in addition to time
- Construct Transform by either matrix or pos+rot

2022-07-02 03:05 UTC, defunctzombie commented on packages/studio-base/src/panels/ThreeDeeRender/transforms/SortedList.ts
> +export class SortedList<K, V> {
Maybe you wanna let this hang out in here for a bit before sharing but this could be a good candidate for `@foxglove/den/collection` - we have some stuff in there already.

Don't know how far along this draft is but it would be good to add tests and comments for this class if you do end up sharing it to den.

2022-07-06 23:29 UTC, jtbandes commented on packages/den/collection/SortedList.ts
> +export class SortedList<K, V> {
I wouldn't call this a List, since lists usually have a single type parameter... How about SortedMap or OrderedMap? Or maybe ListMap / ArrayMap (borrowing names from Java)

2022-07-06 23:40 UTC, jtbandes approved these changes

2022-07-06 23:40 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +  private _updateMaterials(): void {
nit: maybe rename to updateResolution since that's all it does?

2022-07-06 23:40 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/PointCloudsAndLaserScans.ts
> +        pointsHistory.splice(0, pointsHistory.length - 1);
splice returns the deleted elements – you could do `for (const entry of pointsHistory.splice(...))`

2022-07-06 23:40 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/PointCloudsAndLaserScans.ts
> +        pointsHistory.splice(0, pointsHistory.length - 1);
Just curious, how did you track down the fact that this dispose() was missing?

2022-07-07 00:08 UTC, defunctzombie requested changes
SortedList needs some more thought if its gonna go into den

2022-07-07 00:37 UTC, jhurliman commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/PointCloudsAndLaserScans.ts
> +        pointsHistory.splice(0, pointsHistory.length - 1);
It was either the draw count or geometry count, one of those counters was not dropping when I toggled the visibility of a LaserScan topic with decay set.

2022-07-07 00:40 UTC, defunctzombie approved these changes

2022-07-07 19:56 UTC, merged