Refactor playback performance panel to use MUI styling
foxglove/studio pull request #3859
Opened 2022-07-16 12:20 UTC by 2metres

**User-Facing Changes**
Minimal

**Description**
Remove uses of fluentui styles and use MUI typography component

2022-07-18 18:59 UTC, jtbandes approved these changes
Looks ok, might want to improve the contrast in dark mode. Also I reopened #1177 because I noticed it while testing this PR.

2022-07-19 12:35 UTC, defunctzombie requested changes
No more muiStyled please 🙏

2022-07-20 04:14 UTC, defunctzombie approved these changes

2022-07-20 05:18 UTC, 2metres commented
@jtbandes a better indication of contrast issues is represented here: https://603ec8bf7908b500231841e2-qzcwbxmbbh.chromatic.com/?path=/story/components-sparkline--standard this PR increasees the contrast between the chart background and the line itself

2022-07-20 05:19 UTC, merged