Upgrade to React 18.2.0
foxglove/studio pull request #4052
Opened 2022-08-05 01:40 UTC by jtbandes

**User-Facing Changes**
None

**Description**

2022-12-02 04:32 UTC, jtbandes commented
Some day.

2022-12-20 19:31 UTC, defunctzombie commented on packages/studio-base/src/components/MessagePipeline/index.test.tsx
> +// We require two act() calls for each player emit() to take effect because of some quirks with
Do we have any notion of what these quirks are? This is a tough comment to address in the future - maybe by fixing the player emit? if we don't know the quirks.

2022-12-20 19:32 UTC, jtbandes commented on packages/studio-base/src/components/MessagePipeline/index.test.tsx
> +// We require two act() calls for each player emit() to take effect because of some quirks with
Nope. What type of "addressing" are you hoping to see in the future? The app works, and the tests work.

2022-12-20 19:44 UTC, snosenzo commented
Seems to be no lingering `IterablePlayer` leaks anymore from the scrubber after some cursory testing 👍

2022-12-20 19:46 UTC, defunctzombie commented on packages/studio-base/src/components/MessagePipeline/index.test.tsx
> +// We require two act() calls for each player emit() to take effect because of some quirks with
I don't think it is a crazy ask here that this comment do more to explain why we need two act calls when initially we would imagine we only need one? Is it because we update state more than we should? Is it because of strict mode running things twice? Right now this comment tells me we do something because of "react 18" but we went into this imagining we'd only need one act call?

2022-12-20 19:50 UTC, defunctzombie requested changes
I don't follow how the removal of downsampling throttle is part of this PR. If we are using react wrong lets make a separate PR to address that before we upgrade. I'd prefer if this PR focused on the minimal diff required to go from 17->18. Anything we can and should do today with 17 we should merge in preparation for 18.

```
const throttledDownsample = useThrottle(() => downsampleDatasets, 100);
```

2022-12-20 23:30 UTC, jtbandes commented on packages/studio-base/src/components/MessagePipeline/index.test.tsx
> +// We require two act() calls for each player emit() to take effect because of some quirks with
Unfortunately I don't know the reason. I could write that in the comment if that's helpful.

2022-12-21 01:09 UTC, defunctzombie approved these changes

2022-12-21 01:28 UTC, merged