New3d-follow-modes
foxglove/studio pull request #4329
Opened 2022-08-31 21:16 UTC by snosenzo

**User-Facing Changes**
 - add follow modes: stationary , follow and orientation follow modes

**Description**
 - apply followmodes via a new camera group

https://github.com/foxglove/studio/issues/3710

2022-08-31 22:41 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +  private cameraGroup: THREE.Group;
Since the implementation of this feature is pretty finicky and hard to understand, I'd like to see a lot more comments on this variable and the various updated functions below explaining how it works. Will help future maintainers make changes!

2022-08-31 22:42 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +        this.cameraGroup.position.set(0, 0, 0);
How does this work? The comment says we are only making orientation static, but then the code is changing the position?

2022-08-31 22:45 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +      // Snapshot the current pose of the render frame in the fixed frame
This works well while using the app, but since we don't remember this value across reloads, the behavior is a bit weird when you reload the app and the camera is no longer in the same position.

The way this used to work in the old3d panel was that in unfollow mode, `targetOffset` would simply be the camera's position in the fixed frame, so that was actually remembered in the layout... Not sure if doing something equivalent here would make sense?

2022-08-31 23:07 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +        this.cameraGroup.position.set(0, 0, 0);
Will update the comment, but essentially the application of the unfollowPoseSnapshot position and orientation components makes their position static relative to the fixed frame. So when the frame changes the angle of the camera relative to the scene will not change because only the snapshotPose orientation is applied

2022-08-31 23:28 UTC, amacneil commented
Can you add a present tense PR title - see `main` branch commit history for examples

2022-09-01 04:29 UTC, defunctzombie commented
Some things I noticed in the preview deployment:

- Switching from `Follow Position Only` to `Stationary` jumps my viewport to some different part of the scene. I would expect no change in my viewport when moving between these follow modes.
- Consider dropping "Only" from the `Follow Position Only` option
- The `Follow Mode` label should be `Follow mode` to follow the sentence case style we use throughout the app. (Display Frame is also incorrect and should be `Display frame`. https://github.com/foxglove/studio/issues/4335
- `Follow Position` should be `Follow position`
- Consider naming the modes `Pose`, `Position`, `Off`. I am not sure that this is better than `Follow`, `Follow position`, `Stationary` but worth considering.

2022-09-02 20:28 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +  private cameraGroup: THREE.Group;
Hope what I said is enough?

2022-09-02 20:29 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +  private cameraGroup: THREE.Group;
Hope what I said is enough?

2022-09-02 21:03 UTC, snosenzo commented
So where we've landed with this:
- When switching to any of the "follow" modes the targetOffset will be reset so that the user will be centered on the frame center. This is so that the user won't be thrown somewhere relative to the stationary follow mode target offset when switching to a followmode. 
- When switching to the stationary mode the user's target offset and camera center will stay the same
- In stationary mode upon reload it will only keep the same viewstate if playback has not occurred after switching to the current followmode. From talking with Jacob this seemed acceptable since it's not a huge use case and it's very hard to account for without a bunch more work.

2022-09-06 17:41 UTC, defunctzombie commented on packages/studio-base/src/dataSources/SampleNuscenesLayout.json
> -      "followMode": "follow",
The sample layout should not change since that uses the current 3d panel and not 3d beta.

2022-09-06 17:42 UTC, defunctzombie commented on benchmark/src/layouts.ts
> +              followMode: "follow-pose",
Is this a layout for the old 3d panel? If so it shouldn't change?

2022-09-06 17:43 UTC, defunctzombie requested changes
Double check the changes to sample layout and benchmark layouts. I would not have expected those to have any changes.

2022-09-06 17:46 UTC, snosenzo commented on benchmark/src/layouts.ts
> +              followMode: "follow-pose",
ah sorry I didn't realize this was pertaining to the old 3D panel. will change

2022-09-06 18:38 UTC, jtbandes approved these changes

2022-09-06 18:38 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +      this.controls.update();
comment? why do we only need this in follow-pose mode?

2022-09-06 18:38 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/CoreSettings.ts
> +            draft.cameraState.targetOffset = [0, 0, 0];
also reset thetaOffset? And reset only thetaOffset when changing from position -> pose mode?

2022-09-06 19:15 UTC, jhurliman approved these changes

2022-09-06 19:15 UTC, jhurliman commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +        makePose(),
Avoid allocating a new pose every frame. Declare `const snapshotInRenderFrame = makePose();` once globally in this file, since it's a temporary that isn't used across multiple function calls.

2022-09-06 21:06 UTC, merged