3D Panel can cause page freeze
foxglove/studio pull request #4621
Opened 2022-10-12 19:21 UTC by snosenzo

**User-Facing Changes**
n/a

**Description**
 - cycles in the transform tree will throw an error instead of freezing the chrome tab.

Fixes #4618

2022-10-12 22:12 UTC, jhurliman requested changes
Good fix, but a few changes would improve this:

- Cycles are not supported in the tf tree architecture, so it would be nice to detect this at a lower level in the transforms/ code and fail out.
- We should add a test for catching cycles in the transforms/ code
- The user facing changes section of the PR should not be empty, this does affect the end user experience for certain datasets
- The PR title should reflect what is being changed instead of the problem

2022-10-13 19:27 UTC, jhurliman approved these changes
This is definitely an improvement over freezing the app. We may want to surface this error in a more friendly way in the future, but I propose merging this now, and we can follow up with a second PR if that's desirable.

2022-10-13 20:35 UTC, merged

2022-10-13 20:38 UTC, defunctzombie commented
Good stuff. Does the `throw` added in this PR show up as a topic error?

2022-10-13 20:44 UTC, snosenzo commented
It does not, it comes up as a closeable page error. Just opened a thread in slack to discuss where this error should be