Aschimmichanga/event_dialog_renaming
foxglove/studio pull request #4632
Opened 2022-10-13 14:09 UTC by aschimmichanga

**User-Facing Changes**
When the add button is pressed for an event metadata entry, a new empty row is added after the row, not before.

**Description**
Fixing bug found in (this PR)[https://github.com/foxglove/console/pull/1207] 
Also renaming certain variables for code clarity and consistency across both studio and console implementations.

2022-10-14 16:26 UTC, bryfox reviewed
I don't have strong feelings on the variable renaming ("entries" might imply an array of tuples to me, but then again "metadata" might imply the resulting object), so I'll let others review & sign off. But I'm +1 on the `index + 1` to insert below the clicked row.

2022-10-18 17:13 UTC, foxymiles requested changes
Looks fine we just need to move the use-immer dependency into the studio-base package.json instead of top-level.

2022-10-18 17:13 UTC, foxymiles commented on package.json
> +    "use-immer": "0.7.0"
Let's add this to dev dependencies in packages/studio-base/package.json instead.

2022-10-18 19:45 UTC, foxymiles approved these changes

2022-10-18 20:25 UTC, merged