Improve Cyclical Transform Error state
foxglove/studio pull request #4643
Opened 2022-10-14 11:58 UTC by snosenzo

**User-Facing Changes**
 - cyclical transforms will no longer error 3D Panel
 - settings panel errors will appear next to relevant childFrame nodes, and, if relevant, responsible URDF nodes.

**Description**
 - add transform returns whether a cycle was detected or not
 - child frames are still added and can be viewed in UI but are not re-parented to avoid creating cycle
 - responsible URDFs will also get a settings node error

My one issue with this is that it is a little hidden to the user unless they open the Transforms dropdown, since it's on the settings node itself rather than a top-level issue. If it's a subtle mistake in the 3D scene it will not be evident to them.

Fixes #4636

2022-10-14 16:30 UTC, jtbandes commented
> My one issue with this is that it is a little hidden to the user unless they open the Transforms dropdown, since it's on the settings node itself rather than a top-level issue.

Could we just put the error on the Transforms section header instead of the specific frame's node?

2022-10-14 16:31 UTC, snosenzo commented
oh we can we do that? I just wasn't sure that was a thing.  is there an example of where this is done elsewhere?

2022-10-14 16:35 UTC, jtbandes approved these changes

2022-10-14 16:35 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/transforms/TransformTree.ts
> +    return { updated, cycleDetected };
Is it right that there can only be `updated: true, cycleDetected: false`, `updated: false, cycleDetected: true`, and `updated: false, cycleDetected: false`? Makes me wonder if we should just return a 3-state string enum like `"not-updated" | "updated" | "cycle"`. Guess it doesn't make a huge difference.

2022-10-14 16:35 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +        `Transform tree cycle detected: Frame "${parentFrameId}" cannot be the parent of frame "${childFrameId}". Frame was not re-parented`,
```suggestion
        `Transform tree cycle detected: Received transform with parent "${parentFrameId}" and child "${childFrameId}", but "${childFrameId}" is already an ancestor of "${parentFrameId}".`,
```

cc @banisadr for wording suggestions

2022-10-14 17:06 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/transforms/TransformTree.ts
> +    return { updated, cycleDetected };
yeah it could, I kinda prefer having the two boolean values to be more explicit about the status of things that callers of the method might care about. Also makes it a bit more extensible for possible future changes

2022-10-14 17:40 UTC, jhurliman commented
> > My one issue with this is that it is a little hidden to the user unless they open the Transforms dropdown, since it's on the settings node itself rather than a top-level issue.
> 
> Could we just put the error on the Transforms section header instead of the specific frame's node?

Errors being buried is a larger UX issue with Studio that I don't think we should be hacking around as one-offs. Attaching the error to the specific transform provides more information to the user by showing which frame has an ambiguous parent. Taking this in the far opposite direction, we would surface all topic errors in one place at the top level of the app. This is the previous design we moved away from.

2022-10-14 17:44 UTC, jhurliman requested changes
Overall structure looks good, but `addTransform()` is a performance-sensitive method. We can't create a heap allocation for the return value.

2022-10-14 20:44 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/transforms/TransformTree.ts
> +  ): { updated: boolean; cycleDetected: boolean } {
I think it's weird to use a global variable for this without documenting it in the comment above. Would help clarify things if it were accepted as an out parameter as well: `outStatus: {updated:boolean;cycleDetected:boolean}`

All in all, I think I would find a simple string union or `enum AddTransformResult { NOT_UPDATED, UPDATED, CYCLE_DETECTED }` to be clearer code style than returning a reference to a global object.

2022-10-14 23:02 UTC, defunctzombie commented
> Errors being buried is a larger UX issue with Studio that I don't think we should be hacking around as one-offs. Attaching the error to the specific transform provides more information to the user by showing which frame has an ambiguous parent. Taking this in the far opposite direction, we would surface all topic errors in one place at the top level of the app. This is the previous design we moved away from.

Agreed. Let's stick this on the correct node and separately look at how the settings tree or panel need to make users aware of errors when the settings are closed.

/cc @foxymiles @2metres for visibility since yall have talked about this before and want to give you more data points to think about - not trying to go into that discussion here

2022-10-14 23:05 UTC, defunctzombie commented
`Frame was not re-parented` sounds awkward. Is the behavior that we ignore the transform trying to re-parent the frame?

If that is the behavior is to drop the transform let's be clear that is what happens. If the behavior is to include the transform (but not re-parent the frame) what does it mean to keep this transform? If we didn't re-parent the frame what is the purpose of the transform?

2022-10-16 18:55 UTC, snosenzo commented
> Frame was not re-parented sounds awkward. Is the behavior that we ignore the transform trying to re-parent the frame?

I updated to say that `Transform message was dropped.` and also am no longer adding the transform to the child frame when the parent isn't added because I don't think it makes sense to add it. Previously I was just to have as little intervention on the logic as possible, since it's going to show up wrong no matter what. But I think this makes a clearer cut that the message will be dropped and no change will be done.

2022-10-18 23:20 UTC, jhurliman approved these changes

2022-10-19 09:06 UTC, merged