Additional validation for Foxglove.Grid and Support Grids with row padding
foxglove/studio pull request #4651
Opened 2022-10-17 15:46 UTC by snosenzo

**User-Facing Changes**
 - additional validation to foxglove grid
- support grids with row padding (row_stride > column_count * cell_stride)

**Description**
 - added another story to make sure grids with row padding work

Fixes #4650

2022-10-17 17:23 UTC, jtbandes requested changes

2022-10-17 17:23 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/FoxgloveGrid.ts
> +      const message = `FoxgloveGrid column count (${foxgloveGrid.column_count}) or row count (${rows} = data.byteLength / row_stride) is not an integer.`;
```suggestion
      const message = `Grid column count (${cols}) or row count (${rows} = data length ${data.byteLength} / row_stride ${row_stride}) is not an integer.`;
```

2022-10-17 17:23 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/FoxgloveGrid.ts
> +      const message = `FoxgloveGrid data length (${foxgloveGrid.data.length}) is not equal to cols (${cols}) * rows (${rows}) * cell_stride ${cell_stride}`;
```suggestion
      const message = `Grid data length (${foxgloveGrid.data.length}) is not equal to cols (${cols}) * rows (${rows}) * cell_stride ${cell_stride}`;
```

2022-10-17 17:23 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/FoxgloveGrid.ts
>      if (foxgloveGrid.data.length !== size) {
This condition will always be true the way it's currently written. You defined `size` as `row_stride * rows`, and `rows` as `foxgloveGrid.data.byteLength / row_stride`.

Also, the error message doesn't really match what is being checked (we aren't checking cell_stride).

2022-10-17 17:40 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/FoxgloveGrid.ts
>      if (foxgloveGrid.data.length !== size) {
Ah yeah, thanks for catching that. Do we even need this check then? It's not possible to check for the size of the grid to correspond with the length of the array since the length determines the number of rows.

2022-10-18 19:32 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/FoxgloveGrid.ts
>      if (foxgloveGrid.data.length !== size) {
I removed it since the other checks will better validate the data.

2022-10-18 19:37 UTC, jtbandes approved these changes

2022-10-19 09:09 UTC, merged