Create Blank panel for spacing and stuff
foxglove/studio pull request #4692
Opened 2022-10-21 18:40 UTC by 2metres

**User-Facing Changes**
<img width="666" alt="Screen Shot 2022-10-22 at 5 15 02 am" src="https://user-images.githubusercontent.com/924528/197266725-609c8ca4-319a-4a25-8aff-894d0032a5d2.png">

**Description**
Adds blank panel with option foxglove logo.

2022-10-21 18:41 UTC, jtbandes requested changes
This should be an extension.

2022-10-21 18:41 UTC, jtbandes commented
However, it looks like a nice splash screen. Maybe we should add a splash screen to the app 😀

2022-10-21 18:43 UTC, 2metres commented
@jtbandes I tried to start with an extension but couldn't figure it out. Can we pair next week on making it one?

2022-10-21 18:46 UTC, 2metres commented on packages/studio-base/src/panels/Blank/index.stories.tsx
> +NoLogo.parameters = {
@foxymiles can you help me to pass the config to the storybook?

2022-10-21 18:50 UTC, jtbandes commented
Sure I can help out with the extension. Did you try starting with one of the templates/examples e.g. https://github.com/foxglove/create-foxglove-extension/tree/main/examples/panel-settings ?

2022-10-21 18:52 UTC, 2metres commented
I was not aware that existed, Maybe we should make this a blog post as well. Simplist panel I can imagine.

2022-10-21 19:37 UTC, 2metres commented on packages/studio-base/src/panels/Blank/index.stories.tsx
> +NoLogo.parameters = { colorScheme: "both-column" };
@foxymiles can you help me to pass the config to the storybook?

2022-10-25 23:39 UTC, closed without merging

2022-10-25 23:40 UTC, 2metres commented
Closed in favor of adding as an Extension