Remove "Open file by URL" from Welcome dialog
foxglove/studio pull request #4785
Opened 2022-11-09 03:32 UTC by esthersweon

**User-Facing Changes**
- Remove "Open file by URL" from Welcome dialog
- Replace with callout to load data from Data Platform

**Description**
- Also updated desktop app menu to open console directly

2022-11-10 00:35 UTC, jtbandes commented
Are we trying to prevent users from opening remote http files? I don't see anywhere to do that in the UI anymore after this change.

2022-11-10 18:41 UTC, esthersweon commented
@jtbandes - That was my understanding when reading the issue and discussing with @amacneil and @ocin-rye – i.e. we want to make the limits of Studio without Data Platform clearer to the user (and more pressing for them to create an account).

2022-11-10 22:57 UTC, jhurliman commented
For removing the remote loading of bag/mcap over HTTP(S), I propose we follow a deprecation policy similar to other features in the app:

1. Add a warning banner in the Open remote URL dialog that this feature will be removed in a future release, and here's what you should be doing instead: ...
2. Remove Open remote URL from the UI
3. Remove opening remote files via URL
4. Delete the dead code

2022-11-11 02:46 UTC, jtbandes commented
From discussion, we are going to try moving the url flow into the "connection" screen.

2022-11-11 21:44 UTC, amacneil commented
There is no plan to remove "open from URL" functionality. It is still accessible by forming the correct URL, but is not a recommended approach (remote URLs are inherently a bad user experience because many visualizations require downloading the entire file).

2022-11-15 21:13 UTC, esthersweon commented
@jtbandes @amacneil - Updated PR description with latest.

2022-11-16 00:45 UTC, 2metres commented on packages/studio-base/src/components/OpenDialog/Start.tsx
>            void analytics.logEvent(AppEvent.DIALOG_SELECT_VIEW, { type: "remote" });
Should we update this tracking metric to { type: "data-platform" }

2022-11-16 18:40 UTC, jtbandes commented on packages/studio-base/src/components/OpenDialog/Start.tsx
> +        text: "Open remote data...",
What's the thinking with "…" here and not on the other items? I am used to "…" meaning "something will pop up when you click this instead of immediately performing the action". However we've been pretty consistently _not_ using it in our app as far as I know.

2022-11-17 22:15 UTC, esthersweon commented on packages/studio-base/src/components/OpenDialog/Start.tsx
> +        text: "Open remote data...",
Unlike the other options, this will open a separate window outside of the app (to the Console recordings page). Wanted to make that clear.

2022-11-17 22:20 UTC, esthersweon commented on packages/studio-base/src/components/OpenDialog/Start.tsx
> +        text: "Open remote data...",
And I agree with consistency. These instances don't make much sense:

<img width="328" alt="Screen Shot 2022-11-17 at 2 14 34 PM" src="https://user-images.githubusercontent.com/6993359/202572357-4141d147-5031-42ec-a91a-5aa28b93597b.png">

We also don't use it for the docs links. 

Maybe I can remove it here, and then we can revisit the other instances in another PR?

2022-11-17 23:03 UTC, jtbandes requested changes
The remote bag feature doesn't work. I tested with these urls:

https://assets.foxglove.dev/NuScenes-v1.0-mini-scene-0061-f4fbf7b.mcap
https://assets.foxglove.dev/demo.bag

The MCAP file works, but the bag doesn't (for the reason I described in another comment—second player is overwriting the first one). I think you will need logic in the factory that checks the file extension (like how Ros1RemoteBagDataSourceFactory had `supportedFileTypes = [".bag"]`, etc.) and decides which player to create.

2022-11-22 21:40 UTC, esthersweon commented
@jtbandes - Confirmed both remote URLs work (bag and mcap), with most recent changes.

2022-11-23 02:04 UTC, jtbandes approved these changes
Added some final cleanup suggestions but the code looks a lot better!  cc @defunctzombie for a quick review as one of the original authors of the Open Dialog stuff.

2022-11-23 02:04 UTC, jtbandes commented on packages/studio-base/src/dataSources/RemoteDataSourceFactory.ts
> +    const fileExtension = urlParts[urlParts.length - 1];
This is implemented differently than the code above on line 33 – let's try to make them the same since they are both trying to split off the path extension.

2022-11-23 02:04 UTC, jtbandes commented on packages/studio-base/src/players/IterablePlayer/IterablePlayer.ts
> +      } = result;
Irrelevant changes in this file – remove them?

2022-11-23 02:04 UTC, jtbandes commented on packages/studio-base/src/dataSources/RemoteDataSourceFactory.ts
> +  public docsLink = "https://foxglove.dev/docs/studio/connection/ros1-bag";
Is this the right docs link now? Doesn't involve mcap – will we need to update the docs?

2022-11-23 02:10 UTC, jtbandes commented
Can we make this a placeholder value in the field, instead of actually pre-filling the value? Because it never makes sense for someone to click "Open" with the default value here (like it does with the rosbridge & websocket sources)

<img width="464" alt="image" src="https://user-images.githubusercontent.com/14237/203456771-017773d2-d2c0-42ae-bd8c-7f28cbdacc69.png">

2022-11-23 20:12 UTC, esthersweon commented on packages/studio-base/src/dataSources/RemoteDataSourceFactory.ts
> +  public docsLink = "https://foxglove.dev/docs/studio/connection/ros1-bag";
Revised `docsLink` to be `docsLinks` and potentially include more than one URL.

2022-11-24 05:16 UTC, amacneil commented
Per Slack thread, I think we should hold off on merging this until we have a clearly defined goal of what we want users to achieve here.

2022-11-28 23:58 UTC, esthersweon commented
Merging now, based on project meeting conclusion.

2022-11-29 23:56 UTC, foxymiles commented
I reverted the change to the mui theme and just targeted the new fields to reduce the number of visual diffs but otherwise I think this is ok to merge.

2022-11-30 00:21 UTC, 2metres approved these changes

2022-11-30 00:21 UTC, 2metres commented on packages/studio-base/src/components/OpenDialog/FormField.tsx
> +
You can also achieve this by `InputProps={{ notched: false }}`

2022-11-30 03:16 UTC, esthersweon commented on packages/studio-base/src/components/OpenDialog/FormField.tsx
> +
"Property 'notched' does not exist on type 'Partial<InputProps>'."

2022-11-30 03:51 UTC, esthersweon commented
@foxymiles - Thanks for the UI cleanup – I think this is ready to merge too. The only last TODO was slightly revamping the copy, per @amacneil's feedback – just adjusted slightly to include the words "Foxglove Data Platform". 

I added those edits in a final commit:

<img width="787" alt="Screen Shot 2022-11-29 at 7 50 37 PM" src="https://user-images.githubusercontent.com/6993359/204703430-2eb85031-88aa-4ac7-8592-f52b2dd43853.png">

2022-11-30 04:31 UTC, foxymiles commented
The rightmost column looks pretty scrunched now. Should we try to give it a bit more space?

2022-12-05 18:15 UTC, esthersweon commented
@foxymiles - Revised copy to use "team" that we use in other callouts (instead of "organization"):

<img width="785" alt="Screen Shot 2022-12-05 at 10 14 43 AM" src="https://user-images.githubusercontent.com/6993359/205711440-c87b2245-d1ec-43b3-bb75-52d4897bbb9c.png">

2nd column width now looks good.

2022-12-05 18:15 UTC, merged