Foxglove websocket: Fix flickering when receiving messages with interleaved timestamps
foxglove/studio pull request #4984
Opened 2022-12-14 21:55 UTC by achim-k

**User-Facing Changes**
- Foxglove websocket: Fix flickering when receiving messages with interleaved timestamps

**Description**
With this PR, we ignore timestamps on incoming messages and instead set the current time to
- the last server published time message (if the server advertised the `time` capability)
- the current system time (`new Date()`)

This prevents seeks from being detected when messages with interleaving timestamps (from multiple topics) are received

Fixes #3194
Fixes #4917

2022-12-14 21:56 UTC, achim-k commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +      if (this._serverPublishesTime) {
This check is not necessary as the server is only allowed to publish time messages when it advertises the `time` capability

2022-12-14 21:57 UTC, achim-k commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +      this._serverPublishesTime = event.capabilities.includes(ServerCapability.time);
@jhurliman I think we do not have to check the capability here. Just the reception of the first time message is enough, no?

2022-12-14 22:06 UTC, jhurliman requested changes

2022-12-14 22:06 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +      this._serverPublishesTime = event.capabilities.includes(ServerCapability.time);
We need to pick one mode and stick with it for the entire session. So waiting for the first time message won't work, because the spec doesn't guarantee the time message will be sent before any other messages.

2022-12-14 22:06 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +      this._receivedBytes += data.byteLength;
Good catch

2022-12-14 22:06 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +      if (this._serverPublishesTime) {
We should keep this check because we can't switch the behavior of time handling mid-session. I would change it to an `if (!this._serverPublishesTimes) { return; }` though to avoid indenting the whole callback.

2022-12-14 22:06 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +        endTime: currentTime,
I think we lost the logic for "`/clock`" mode where endTime can be > currentTime

2022-12-14 22:06 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +    return this._clockTime ?? fromMillis(Date.now());
This doesn't look right. If we are in "clock mode" but _clockTime hasn't been set yet, it will return the current timestamp and then switch to a different time source mid-session once the first time message is received. One option is to remove the `_serverPublishesTime` boolean and instead set `_clockTime` to 0.

2022-12-14 22:35 UTC, defunctzombie commented
From the point of view of clients this is breaking behavior in studio. We no longer use the receiveTime they send whereas before we did. I don't have intuition one way or the other but I do want to call that out so we are deliberate in what we are doing here and prepared to communicate accordingly if questions come up around this.

@jtbandes

2022-12-14 22:44 UTC, jtbandes commented
Is there some way we could keep the current behavior as default for a while but get people to switch, or change the default but provide some backwards compatible mode?

2022-12-20 20:02 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +        ++this._lastSeekTime;
Calling this variable `Time` when it's really an incrementing counter is confusing. We should either rename the variable or use it to store actual timestamps.

2022-12-20 20:04 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +      this._startTime = currentTime;
It looks like this does not correctly handle the case where you connect part-way through bag playback, then the time loops back to a timestamp earlier than what the client has observed.

2022-12-20 21:45 UTC, jtbandes commented
Decisions and context from team meeting today:
- We do not believe there are a large number of users depending on the old behavior, so it's okay to break it by switching to use the system clock instead of the receiveTime sent by the server.
  - However, we need to provide a smooth migration path, so we should add support for the new clock op first, talk about it and the planned change in release notes, and then switch to use the system clock by default after another 1 or 2 releases (rather than doing them at the same time as currently done in this PR).
- We do not believe there are any significant app behaviors that will work differently when using the system clock instead of the receiveTime.

2022-12-21 17:04 UTC, achim-k commented
> However, we need to provide a smooth migration path, so we should add support for the new clock op first, talk about it and the planned change in release notes, and then switch to use the system clock by default after another 1 or 2 releases (rather than doing them at the same time as currently done in this PR).

I will close this PR and open two separate PRs to impoement the proposed migration strategy

2022-12-21 17:04 UTC, closed without merging