Saving User scripts updates subscribed panels
foxglove/studio pull request #5071
Opened 2023-01-04 17:46 UTC by snosenzo

**User-Facing Changes**

- Saving a user script will update subscribed panels with new output messages

**Description**
 Added an optional `requestBackfill` method to the player API, since we need the `UserNodePlayer` to request backfill without having to go through `seek` on the `IterablePlayer`. The reason we have to add an explicit public function for it is because we have logic in the `IterablePlayer` preventing seeking to the currentTime. 
Couple of thoughts: It might be better if we could only backfill the relevant input topics to the nodes, but that might complicate the API for this single usecase. Also the `_bufferedSource.getBackfilledMessages` only returns the most recent messages for each topic, unsure how this might impact preloading of tf's in the future. 

Fixes #4989
FG-1019

2023-01-04 17:49 UTC, defunctzombie requested changes
Please let's avoid adding a requestBackfill method to the player API. I felt pretty strongly that this was a weird anti-pattern for the player interface and worked to purge it from our code in favor of the player updating when it gets subscriptions.

If the user script needs to re-process the current frame I think it should do that within its own logic.

2023-01-04 20:37 UTC, snosenzo commented
> Please let's avoid adding a requestBackfill method to the player API. I felt pretty strongly that this was a weird anti-pattern for the player interface and worked to purge it from our code in favor of the player updating when it gets subscriptions.
> 
> If the user script needs to re-process the current frame I think it should do that within its own logic.

Ah okay, good to know. I refactored to make the `UserNodePlayer` keep track of last previous input messages and to reprocess them when the UserNodes are updated. Let me know if this isn't desirable, the last option I have in mind is to unsubscribe and re-subscribe to the input topic, but that felt a little hacky

2023-01-05 20:37 UTC, defunctzombie commented on packages/studio-base/src/players/UserNodePlayer/index.ts
> +          messagesForRecompute.length > 0 ? messages.concat(messagesForRecompute) : messages;
Does this not end up with some duplicate messages? Is the assumption here that `messages` is empty? If any items in `messages` match any items in `_lastMessageByInputTopic` then we end up with duplicate messages into the _getMessages call?

2023-01-05 20:37 UTC, defunctzombie reviewed
Does this also run for preload messages nodes? So if I plot the output of a user script and then update that script, does my plot update?

2023-01-05 21:58 UTC, snosenzo commented
@defunctzombie 
> does my plot update

confirmed that it does work with plot view

> duplicate messages?

good catch -- I added some logic to make sure input topics to get messages from were unique and that it wouldn't use old messages if a message with a topic to be updated was in active state.

2023-01-06 13:48 UTC, defunctzombie approved these changes
Check that this also works on preloaded messages and I think this is good to go.

2023-01-06 16:18 UTC, merged