Bypass debounce for interactive settings edits in 3d
foxglove/studio pull request #5156
Opened 2023-01-17 00:41 UTC by foxymiles

**User-Facing Changes**
Improves interactivity of edits to 3d panel settings fields.

**Description**
This bypasses the debounce for interactive edits in 3d settings fields by optionally allowing callers of `updateSettingsTree` to force an immediate flush of the debounced function and updating the `saveSetting` function, which is called by interactive action handlers, to always immediately call for immediate updates.

2023-01-17 19:03 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/SceneExtension.ts
> +    write: "immediate" | "debounced" = "immediate",
why change the default for all settings saves? Maybe the default should be debounced and we use immediate in a few places we need it? Or maybe there should be no default so the caller is forced to choose one?

2023-01-17 21:40 UTC, foxymiles commented on packages/studio-base/src/panels/ThreeDeeRender/SceneExtension.ts
> +    write: "immediate" | "debounced" = "immediate",
From what I can tell `saveSettings` is mainly called by the action handlers, so these will be coming from user-initiated edits, all of which we'd want to flush immediately to avoid the caret positioning problem.

@jhurliman does that sound right?

2023-01-18 06:55 UTC, jhurliman commented on packages/studio-base/src/panels/ThreeDeeRender/SceneExtension.ts
> +    write: "immediate" | "debounced" = "immediate",
My understanding is user-initiated edits can happen at vsync rate if you are dragging a slider back and forth. I think those need to be debounced.

2023-01-19 21:22 UTC, jhurliman commented
> If the interactive scrubbing is the only issue maybe we should just debounce the updates from that before they hit the action handlers?

That could work

2023-02-13 14:54 UTC, defunctzombie commented
My first glance at this is that it is not a great devx for the extension author. Why do I need to select “direct” or “scrubbing” - both are interactions with the input. The description on direct says “direct user interactions with the input” - how is that different than when I scrub? That is a direct interaction.

I am 👎 based on the current PR description. I would push for us to handle this better or find a simpler way for the extension author to ensure proper behavior. The proposal here _feels_ like it introduces more confusion.

2023-02-14 15:18 UTC, defunctzombie commented
@foxymiles What is the difference in behavior I would observe as a panel author for `direct` vs `scrubbing`?

2023-02-14 22:51 UTC, foxymiles commented
@defunctzombie The only difference is the speed of updates. `scrubbing` updates can arrive at `requestAnimationFrame` rates, so 60+hz. For most panels this is immaterial but for panels with very complex settings like 3d you may want to debounce only those high frequency messages.

Maybe there's better terminology than `direct` vs `scrubbing`? I also considered just having an `isScrubbing` boolean.

2023-02-15 02:37 UTC, defunctzombie commented
> Maybe there's better terminology than `direct` vs `scrubbing`? I also considered just having an `isScrubbing` boolean.

I think my hangup is that it feels like maybe the move here is to expose the extension author to the debounce concept here any maybe let them configure some delay? Then as an author I can be clear that what I am doing is selecting the delay for updates on this field. I personally did not find `direct` or `scrubbing` very obvious terms that I could translate into how it would impact my settings updates.

Maybe see if others share my feelings or are ok with direct vs scrubbing (or have other terms that are even more clear). I don't mind the concept of allowing an extension author to control a delay here but I think we should consider the terms we want to use.

2023-02-15 02:40 UTC, foxymiles commented
I considered allowing panel authors to configure this on a per-field basis but the way that 3d implements settings would require quite a bit of extra work to set this on all the various renderables that can contribute fields to the rendered tree. It also seems to me that it's something we'd want to debounce for any numeric input in the 3d panel.

Maybe @jhurliman has some better ideas?

2023-02-17 19:47 UTC, jhurliman approved these changes

2023-02-17 21:11 UTC, defunctzombie requested changes
I want to take a look at this because I am not a fan of the proposed terms.

2023-03-01 23:05 UTC, foxymiles commented
Closed in favor of https://github.com/foxglove/studio/pull/5419

2023-03-01 23:05 UTC, closed without merging