Fix type definitions in studio/index.d.ts
foxglove/studio pull request #5227
Opened 2023-01-25 21:51 UTC by jtbandes

**User-Facing Changes**

**Description**

2023-01-26 01:34 UTC, jtbandes commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +    );
@jhurliman @achim-k it seems like the incoming value can be `undefined`, but the `@foxglove/ws-protocol` package doesn't accept `undefined` params. What should we do here?

2023-01-26 01:34 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
> -      context.setVariable(SELECTED_ID_VARIABLE, id ?? ReactNull);
@jhurliman any idea why null was used here explicitly?

2023-01-26 17:14 UTC, achim-k commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +    );
The spec currently does not allow setting parameter values to `undefined` (I guess that means removing them?). Should we add that?

2023-01-26 21:15 UTC, jhurliman commented on packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
> -      context.setVariable(SELECTED_ID_VARIABLE, id ?? ReactNull);
Using `undefined` was causing the variable to be removed entirely, where it should be set to empty here but not removed.

2023-01-26 21:16 UTC, jhurliman commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +    );
One option is to update `ws-protocol` to allow `undefined` for params, and delete params that are set to `undefined`.

2023-01-27 13:38 UTC, achim-k commented on packages/studio-base/src/players/FoxgloveWebSocketPlayer/index.ts
> +    );
Yes we could do that. It's not a breaking change. Will create a ticket for that.

2023-02-14 00:00 UTC, jtbandes commented on packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx
> -      context.setVariable(SELECTED_ID_VARIABLE, id ?? ReactNull);
Looks like this isn't working on main now, so I think it's ok to proceed with this change.

2023-02-14 00:01 UTC, jtbandes commented on packages/studio-base/src/players/Ros1Player.ts
> +        this._parameters = new Map(rosNode.parameters as Map<string, ParameterValue>);
@jhurliman @achim-k Let me know if you can think of better ideas here. Does the ros 1 param server actually support these types (Date, Uint8Array, Record<string,XmlRpcValue>)?

2023-02-15 02:03 UTC, defunctzombie commented on packages/studio-base/src/players/Ros1Player.ts
> +        this._parameters = new Map(rosNode.parameters as Map<string, ParameterValue>);
We have learned that it does (from what I read in slack). So why do we need the cast here?

2023-02-15 02:05 UTC, defunctzombie commented on packages/studio-base/src/components/VariablesSidebar/Variable.tsx
> +      setGlobalVariables({ [name]: newVal as VariableValue });
Should we add a check that `newVal` conforms to `VariableValue` types? In recent times I've started to prefer type narrowing functions rather than `as` casts since these tend to surface as errors later when we are wondering why something downstream is failing.

2023-02-15 02:07 UTC, defunctzombie requested changes
I don't understand this change in `studio-base/tsconfig.json`. This does not align with how we've been using the package specific `tsconfig.json` files.
```
"rootDir": "..",
```

2023-02-16 18:23 UTC, jtbandes commented on packages/studio-base/src/components/VariablesSidebar/Variable.tsx
> +      setGlobalVariables({ [name]: newVal as VariableValue });
This comes from a JSON.parse. We treat that as unknown so it needs a cast. I am not sure what would be an appropriate level of validation but I feel like somehow doing something like a full ajv schema is overkill. Writing a validator by hand that appropriately handles arrays and nested objects would also feel like overkill.

2023-02-16 18:30 UTC, jtbandes commented on packages/studio-base/tsconfig.json
> +    "rootDir": "..",
Are these a concern too?

<img width="254" alt="image" src="https://user-images.githubusercontent.com/14237/219455619-2c8f9fdd-5cbb-4d47-9668-fef02dfef8d9.png">

2023-02-17 01:03 UTC, defunctzombie approved these changes

2023-02-17 01:43 UTC, merged