Move Variables into right sidebar
foxglove/studio pull request #5276
Opened 2023-02-01 01:07 UTC by 2metres

**User-Facing Changes**
Introduces Right Sidebar and moves Variables and Events into it.

<img width="1800" alt="Screen Shot 2023-02-01 at 12 06 39 pm" src="https://user-images.githubusercontent.com/924528/215920002-f4d7c88f-0839-43a2-9a0e-37eeb1022de4.png">

2023-02-01 01:08 UTC, 2metres commented
Todo 
- [ ] Make right sidebar resizeable/collapsible
- [ ] Connect selected object to sidebar

2023-02-23 20:15 UTC, jtbandes commented on packages/studio-base/src/components/TabPanel.tsx
> +export function TabPanel(
This is an extremely confusing component name since we also have the `Tab` component, which is a Panel.

2023-02-23 20:17 UTC, jtbandes commented on packages/studio-base/src/components/TabPanel.tsx
> +export function TabPanel(
I also don't get what this component is for. Its main functionality seems to be wrapping children in a `<div>` and conditionally hiding them. Doesn't really sound like it does much tab-related stuff?

2023-02-23 20:18 UTC, jtbandes commented on packages/studio-base/src/components/Sidebar/index.stories.tsx
> +      <MockMessagePipelineProvider>
I haven't read through yet to see why this is added, but with no other context, it seems wrong that we would need the MessagePipeline context in a story that's just about the Sidebar component (which handles tabs & layout of other components)

2023-02-23 20:21 UTC, jtbandes commented on packages/studio-base/src/components/SecondarySidebar.tsx
> +            <VariablesSidebar />
Seems like maybe this component is due to be renamed given that it is not a sidebar in itself?

2023-02-23 20:28 UTC, jtbandes commented on packages/studio-base/src/components/SecondarySidebar.tsx
> +export function SecondarySidebar({
Not sure about "secondary" naming... maybe "RightSidebar"? Are we planning to also have one of these on the left as well, eventually, or totally remove the left one?

2023-02-23 20:28 UTC, jtbandes commented on packages/studio-base/src/components/SecondarySidebar.tsx
> +  const playerSourceId = useMessagePipeline(selectPlayerSourceId);
(related to my comment in Sidebar stories) - let's refactor this component so it handles layout only, and leave the decision on what content to show in the Workspace component, like we do for the left sidebar. It's confusing to have the two sidebars be so different, and it also clutters up the tests/stories with providers that seem irrelevant to the concept of a sidebar.

2023-02-23 20:28 UTC, jtbandes commented on packages/studio-base/src/components/Sidebar/index.tsx
> +            <BracesVariable20Filled />
From a usability perspective, I find it confusing that icons are shown on the right, but when I click one, it disappears and is replaced with text.

2023-02-23 20:28 UTC, jtbandes commented on packages/studio-base/src/components/Sidebar/index.tsx
>              // keep previous splitPercentage when changing from one tab to another
I would think we probably want similar functionality for the sidebar on the right, right? I can't actually test this out easily because the preview deployment doesn't let me log in...

2023-02-23 20:28 UTC, jtbandes commented on packages/studio-base/src/components/Sidebar/index.tsx
> +            // keep previous splitPercentage when hiding the right bar
not sure what this comment means but it does appear that the left bar changes width when I hide/show the right bar, so I think something is broken

2023-02-23 20:29 UTC, jtbandes commented
This PR's "user-facing changes" should take into account that this is all behind a feature flag. I would write "None (feature flagged)" for user-facing changes.

2023-02-23 22:09 UTC, foxymiles commented on packages/studio-base/src/components/Sidebar/index.tsx
>              // keep previous splitPercentage when changing from one tab to another
We only have one "tab" on the right side right now.

2023-02-23 22:21 UTC, jtbandes commented on packages/studio-base/src/components/Sidebar/index.tsx
>              // keep previous splitPercentage when changing from one tab to another
Ah I saw two in the screenshot, thought Events would be there too? I guess I'll pull and test locally.

2023-02-23 22:23 UTC, foxymiles commented on packages/studio-base/src/components/Sidebar/index.tsx
>              // keep previous splitPercentage when changing from one tab to another
There is an issue though with toggling the right bar changing the width of the left. Working on it.

2023-02-23 22:30 UTC, jtbandes commented on packages/studio-base/src/components/Sidebar/index.tsx
>              // keep previous splitPercentage when changing from one tab to another
There are two tabs when you have a DP source loaded. However, it does seem to somehow remember the splitPercentage of the right sidebar...not sure how that's working 🤷   And yeah I did see the issue you mentioned with the right sidebar changing the left width and vice versa.

![image](https://user-images.githubusercontent.com/14237/221045316-b34704e2-8048-4222-80cc-6c1f113e072b.png)

2023-02-23 22:32 UTC, foxymiles commented on packages/studio-base/src/components/Sidebar/index.tsx
>              // keep previous splitPercentage when changing from one tab to another
I think the term "tab" here is becoming a bit confusing here. The splitPercentage logic for the left side was to keep the sidebar width the same when changing between different items on the vertical sidebar. These are internal to the right sidebar.

In any case the current logic isn't right so I'll work on it.

2023-02-23 23:04 UTC, jtbandes requested changes
Various UX and architecture issues raised in prior comments

2023-02-24 00:17 UTC, amacneil commented
Getting this crash in 3d panel, not sure if related to this PR
<img width="1346" alt="image" src="https://user-images.githubusercontent.com/637671/221060832-a91143cb-012c-4422-bc70-f337fc4666e9.png">

2023-02-24 00:28 UTC, amacneil commented
Closing and opening the left sidebar takes it to take up 80%

2023-02-24 00:53 UTC, foxymiles commented
> Closing and opening the left sidebar takes it to take up 80%

Good catch. Should be fixed now.

2023-02-24 18:00 UTC, defunctzombie commented
There's a good number of eyeballs on this from technical and product so I will remove myself as a reviewer of this. I'll definitely take a poke at it once it has merged and I can enable the feature flag to see it.

2023-02-27 23:34 UTC, 2metres commented on packages/studio-base/src/components/TabPanel.tsx
> +export function TabPanel(
This is largely based on [examples from MUI](https://mui.com/material-ui/react-tabs/#basic-tabs), they even export a version in `mui/lab`

2023-02-27 23:35 UTC, 2metres commented on packages/studio-base/src/components/SecondarySidebar.tsx
> +  const playerSourceId = useMessagePipeline(selectPlayerSourceId);
@foxymiles can you address this request?

2023-02-27 23:56 UTC, foxymiles commented on packages/studio-base/src/components/SecondarySidebar.tsx
> +  const playerSourceId = useMessagePipeline(selectPlayerSourceId);
The `Sidebar` component now would be more accurately called something like `SidebarsLayout` since it now contains both left & right sidebars and the content of the layout itself. Not sure if we want to expand the scope of the PR to make that change.

2023-02-28 00:10 UTC, foxymiles commented on packages/studio-base/src/components/SecondarySidebar.tsx
> +  const playerSourceId = useMessagePipeline(selectPlayerSourceId);
I've lifted the message pipeline stuff up into the workspace.

2023-02-28 00:23 UTC, 2metres commented on packages/studio-base/src/components/Sidebar/index.tsx
> +            <BracesVariable20Filled />
I feel like this pattern is fairly inuitive. 

When in the collapsed state they are minimized they are icons when epanded they are tabs. You can jump to the expanded item by clicking the icon.

2023-02-28 00:26 UTC, 2metres commented
> Getting this crash in 3d panel, not sure if related to this PR <img alt="image" width="1346" src="https://user-images.githubusercontent.com/637671/221060832-a91143cb-012c-4422-bc70-f337fc4666e9.png">

I am seeing this crash pretty regularly on localhost: 

```
Error
Unsupported color mode gradient
Call Stack
 paletteColorCached
  packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts:415:15
 updateTexture
  packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts:305:13
 OccupancyGrids._updateOccupancyGridRenderable
  packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts:227:9
 OccupancyGrids.handleOccupancyGrid [as handler]
  packages/studio-base/src/panels/ThreeDeeRender/renderables/OccupancyGrids.ts:128:18
 handleMessage
  packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts:1038:26
 Renderer.addMessageEvent
  packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts:836:9
 eval
  packages/studio-base/src/panels/ThreeDeeRender/ThreeDeeRender.tsx:562:22
 invokePassiveEffectCreate
  node_modules/react-dom/cjs/react-dom.development.js:23484:20
 HTMLUnknownElement.callCallback
  node_modules/react-dom/cjs/react-dom.development.js:3947:14
 Object.invokeGuardedCallbackDev
  node_modules/react-dom/cjs/react-dom.development.js:3996:16
```

2023-02-28 00:28 UTC, foxymiles commented
> I am seeing this crash pretty regularly on localhost:

It's hard to see how the changes in this PR might have triggered that. Do you see it on main?

2023-02-28 00:34 UTC, 2metres commented
Yeah, fair seeing something similar on Production

2023-02-28 03:40 UTC, 2metres commented on packages/studio-base/src/components/Sidebar/index.tsx
> +            <BracesVariable20Filled />
Following @jtbandes and I's discussion opting for toggle in the Top Nav to open close the sideflaps

2023-02-28 05:08 UTC, 2metres commented on packages/studio-base/src/components/TabPanel.tsx
> +export function TabPanel(
I have renamed TabContent to try and clarify that it's not related to Foxglove "Panels"

2023-03-01 01:56 UTC, jtbandes approved these changes
Basically a self-approval at this point
![image](https://user-images.githubusercontent.com/14237/222024857-0bec77a2-b332-4d79-869f-f112c8a388b6.png)

2023-03-01 03:01 UTC, merged