Fix Studio Snap package not being able to access `$HOME/.foxglove-studio`
foxglove/studio pull request #5280
Opened 2023-02-01 20:29 UTC by achim-k

**User-Facing Changes**
- Fix Studio Snap package not being able to access `$HOME/.foxglove-studio`

**Description**
This PR adds a snap plug for the `personal-files` interface, which allows accessing hidden files in the user's home directory. This fixes https://github.com/foxglove/create-foxglove-extension/issues/89

Details:
> 
> The Studio snap does have the home interface, but not the personal-files interface:
> 
> - The Snap ['home' interface](https://forum.snapcraft.io/t/the-home-interface/7838) permits access only to **non-hidden** files and directories in a user's /home (and nowhere else).
> 
> - The Snap ['personal-files' interface](https://snapcraft.io/docs/personal-files-interface) permits access to **all files** and directories in a user's /home (and nowhere else).
> 
> ```
> $ snap connections foxglove-studio
> Interface                 Plug                             Slot                             Notes
> home                      foxglove-studio:home             :home                            -
> 
> $ snap connections firefox 
> Interface                 Plug                            Slot                             Notes
> home                      firefox:home                    :home                            -
> personal-files            firefox:dot-mozilla-firefox     :personal-files                  -
> ```
> 

Before merging this PR, we have to request permission to use the `personal-files` for the studio snap:

- [ ] `personal-files` is super-privileged, permission to use it has to [be requested](https://snapcraft.io/docs/auto-connection-mechanism#heading--super)
- [ ] `personal-files` does not automatically connect but can be enabled for a specific snap by request ([instructions](https://snapcraft.io/docs/process-for-aliases-auto-connections-and-tracks))

2023-02-01 20:32 UTC, achim-k commented on electron-builder.json
> +      "HOME": "$SNAP_REAL_HOME",
This took me hours to figure out. `$HOME` is effectively set to `$SNAP_USER_DATA` for confined snaps and in order to access the user's home folder, we have to set `$HOME` to `$SNAP_REAL_HOME`. (https://forum.snapcraft.io/t/solved-help-needed-using-personal-files-interface/14031/2)

2023-02-01 20:44 UTC, jhurliman approved these changes

2023-02-01 21:05 UTC, defunctzombie commented
👍 I will send this PR over to our Canonical contacts and ask them to take a look and give feedback on this approach.

Does changing `$HOME` from `$SNAP_USER_DATA` mean that desktop users with layouts will lose all those because we will be changing the folder where we would be looking for those? Sounds pretty unpleasant if you lose your layouts (and are not signed in - i.e. local only user).

What would be our fall-back plan? Is there some way to have `yarn local-install` (for the create-extension scripts) have a `--snap` mode or accept a path to install to? Can we write to `$SNAP_USER_DATA` of the snap or is that protected?

2023-02-01 21:10 UTC, defunctzombie requested changes
Placing a hold on this PR until we hear back from the Canonical engineers and until we can answer the question about existing layouts.

2023-02-01 21:22 UTC, RomainLLC commented
Hi, thanks for this.

Is there any way to fiw it on already installed snap Foxglove ?

I'm looking in the /snap/foxglove-studio/current/meta/snap.yaml file but hard to understand if the params can be fixed here.

2023-02-02 19:57 UTC, achim-k commented
> What would be our fall-back plan? Is there some way to have `yarn local-install` (for the create-extension scripts) have a `--snap` mode or accept a path to install to? Can we write to `$SNAP_USER_DATA` of the snap or is that protected?

We decided to make changes to the install script to additionally install extensions into the snap's data directory. See https://github.com/foxglove/create-foxglove-extension/pull/91

I will close this PR to avoid the mentioned problem with current snap users losing their existing layouts / templates,

2023-02-02 19:57 UTC, closed without merging