Support ZFP-compressed images in the Image and 3D panel
foxglove/studio pull request #5397
Opened 2023-02-19 06:57 UTC by jhurliman

**User-Facing Changes**
- Adds support for ZFP-compressed images to the Image and 3D panels

**Description**
ZFP image support is a generic solution for depth images or other two-dimensional data requiring >8-bit depth, in situations that benefit from  message-level compression such as live streaming or lossy storage. Lossy and lossless modes are supported. The ZFP data must be packaged in a `foxglove.CompressedImage` or `sensor_msgs/CompressedImage` message with `format="zfp"`. Only two-dimensional data is supported, and the compressed stream must be prefixed with a full ZFP header.

2023-02-21 00:59 UTC, defunctzombie commented
With `format="zfp"` how do you know what they underlying image/data format? From what I've been able to read about `zfp` this would be similar to seeing `format="gzip"` which is not an image format by itself.

Do you have corresponding schema repo or docs updates (or drafts) that we can read about how we would present this to the user and how we'd need the user to format their data?

2023-02-22 16:27 UTC, snosenzo commented on packages/den/image/decodings.ts
> +let zfpBuffer: ZfpBuffer | undefined;
is it possible for this to be used by two different asynchronous decodings at the same time? Could this be an issue?

2023-02-23 04:49 UTC, defunctzombie requested changes
Holding until we can do more research into alternative approaches and get feedback from the customer: https://github.com/foxglove/website/pull/997#issuecomment-1441214313

2023-02-23 19:25 UTC, jhurliman commented on packages/den/image/decodings.ts
> +let zfpBuffer: ZfpBuffer | undefined;
Yes, it's possible because the `wasm-zfp` module is single-threaded.

2023-04-05 14:51 UTC, defunctzombie commented
Closing. See comment: https://github.com/foxglove/website/pull/997#issuecomment-1497624043

2023-04-05 14:51 UTC, closed without merging

2023-04-05 17:13 UTC, jtbandes commented
Copying the linked comment here for public visibility:

> Closing this. I do not think "zfp" is correct as a "format" peer to "png" or "jpeg". I could see us adding a compression field to RawImage and using "zfp" there as generic compression format for certain kinds of byte data. That seems more aligned with what is happening here with the `mono16` data.
> 
> We've also learned that png itself can store mono16 data.