New UI: Show new left sidebar and hide old sidebar
foxglove/studio pull request #5476
Opened 2023-03-03 02:04 UTC by 2metres

**User-Facing Changes**
None

**Description**
Update left nav to use new style sidebar under feature flag

2023-03-03 22:49 UTC, jtbandes commented on packages/studio-base/src/Workspace.tsx
> +  }, []);
might be a little cleaner as useCallback rather than useMemo

2023-03-06 23:34 UTC, 2metres commented on packages/studio-base/src/Workspace.tsx
> +  }, []);
We have a mixture of `useMemo` and `useCallback` here. Should I prefer one over the other?

2023-03-06 23:34 UTC, jtbandes commented on packages/studio-base/src/Workspace.tsx
> +  }, []);
Usually useCallback when the thing is a function and useMemo otherwise

2023-03-07 06:57 UTC, jtbandes requested changes
Spacing adjustments make storybook changes hard to review :(
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/14237/223346685-e30e0e80-585c-4e4f-8785-25e4d31f4788.png">

These stories look wrong:
<img width="1314" alt="image" src="https://user-images.githubusercontent.com/14237/223347083-103d1cfe-3eb2-4ef6-8d66-dc56b25883e6.png">

2023-03-07 09:19 UTC, 2metres commented
> These stories look wrong: <img alt="image" width="1314" src="https://user-images.githubusercontent.com/14237/223347083-103d1cfe-3eb2-4ef6-8d66-dc56b25883e6.png">

What looks wrong about them? Should we add test for the new UI?

2023-03-07 16:05 UTC, amacneil commented
Panel settings does not open when I click a panel's cog icon.

2023-03-08 20:55 UTC, jtbandes approved these changes
Code changes looking good but a couple of the stories are missing their sidebar.

2023-03-08 20:57 UTC, jtbandes commented on packages/studio-base/src/components/Sidebars/NewSidebar.stories.tsx
> +  enableAppBar?: boolean;
Looks like this prop is unused now

2023-03-08 21:22 UTC, jtbandes commented on packages/studio-base/src/components/Sidebars/NewSidebar.stories.tsx
> +export const RightOpen = (): JSX.Element => <Story />;
Is this story doing anything at all?

2023-03-08 22:13 UTC, jtbandes approved these changes

2023-03-08 22:25 UTC, amacneil commented
Product review feedback:
- Remove left sidebar "open data source" button for now
- Right hand sidebar needs to be wider by default

Follow up meeting about panel settings position

2023-03-09 03:39 UTC, merged