Restyle Data Source info so that Layout Name is in the header
foxglove/studio pull request #5607
Opened 2023-03-22 00:18 UTC by 2metres

**User-Facing Changes**
<img width="534" alt="Screen Shot 2023-03-22 at 11 06 41 am" src="https://user-images.githubusercontent.com/924528/226770310-8b76ae84-22d9-4674-adb6-c4019783af32.png">

**Description**

2023-03-22 00:19 UTC, 2metres commented
Need help getting the Layout name. Currently it's fairly difficult

2023-03-22 00:37 UTC, jtbandes commented
Can we make the layout name also be present when no data source is selected?

2023-03-28 04:14 UTC, 2metres commented
@foxymiles I've managed to retrieve the Layout ID but could you help to return the layout name?

2023-03-30 04:33 UTC, amacneil commented
- move layouts to the right
- make the text white
- keep the data source clickable for now (as you have in this pr)
- probably drop the external link icon for now

2023-03-31 01:46 UTC, foxymiles approved these changes

2023-04-02 23:30 UTC, defunctzombie commented on packages/studio-base/src/components/AppBar/DataSource.tsx
> +import { ErrorCircle20Filled, Open16Filled } from "@fluentui/react-icons";
What relationship does this change (styling the data source) have to the PR? If we can we should leave unrelated changes for separate PRs so when we review we know what change we are reviewing.

2023-04-02 23:31 UTC, defunctzombie requested changes
Putting a hold on this PR from slack discussion. We'll use a different approach here.

2023-04-03 01:58 UTC, defunctzombie commented
I think we should replace this PR with https://github.com/foxglove/studio/pull/5687 and move the data source changes to a separate PR.

2023-04-03 04:41 UTC, amacneil commented on packages/studio-base/src/components/AppBar/DataSource.tsx
> +import { ErrorCircle20Filled, Open16Filled } from "@fluentui/react-icons";
That was actually the original project. It morphed into mostly a layout menu change and reverting most (I thought all but I guess not) of the data source name changes.

<img width="822" alt="image" src="https://user-images.githubusercontent.com/637671/229413050-d7494a94-6640-4314-9057-2dfd526585c2.png">

2023-04-04 00:38 UTC, defunctzombie approved these changes

2023-04-04 00:39 UTC, merged