Rename preferences to settings without refactoring all component naming
foxglove/studio pull request #5767
Opened 2023-04-13 05:54 UTC by 2metres

**User-Facing Changes**
Preferences are now called Settings

[Simplified Chinese translation from this resource](https://dictionary.cambridge.org/dictionary/english-chinese-simplified/setting#caldcns-1-2-2)

2023-04-13 16:03 UTC, jtbandes commented on packages/studio-base/src/i18n/zh/preferences.ts
> +  preferences: "设置",
@Woodii1998 can you double-check this?

2023-04-13 16:03 UTC, jtbandes commented on packages/studio-base/src/i18n/en/preferences.ts
>  export const preferences = {
I think we should probably rename this too, to maybe `appSettings`? There's already some precedent in that we use AppSetting as the name of an enum.

2023-04-14 00:25 UTC, 2metres commented on packages/studio-base/src/i18n/en/preferences.ts
> +  preferences: "Settings",
Mainly was trying to minimize the impact of this change. Theoretically we could go as far as renaming the whole component to SettingsDialog.

2023-04-14 03:38 UTC, jtbandes commented on packages/studio-base/src/i18n/en/preferences.ts
> +  preferences: "Settings",
Sounds like a good plan to me - maybe AppSettingsDialog? Just to differentiate from panel settings. Up to you, but I think having both preferences and settings throughout the code is (already and will continue to be) confusing

2023-04-14 16:40 UTC, jtbandes requested changes
Would like to see more renaming of variables & components

2023-04-17 19:28 UTC, esthersweon commented on packages/studio-base/src/i18n/en/preferences.ts
> +  preferences: "Settings",
Agree re: renaming components to match the copy.

2023-04-17 23:55 UTC, jtbandes approved these changes

2023-04-17 23:57 UTC, merged

2023-04-18 06:12 UTC, amacneil commented
👍 nice

2023-04-18 06:20 UTC, Woodii1998 commented on packages/studio-base/src/i18n/zh/preferences.ts
> +  preferences: "设置",
Sorry for not noticing this message, the translation to '设置' is correct