Remove unused TypicalFilterName code
foxglove/studio pull request #5821
Opened 2023-04-25 02:50 UTC by defunctzombie

**User-Facing Changes**
None

**Description**

2023-04-25 02:51 UTC, jtbandes commented on packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts
> -            newPath = `${path}[:]{${name}==${arrayElement[name]}}`;
If this is not an observable change, what are we using the `newPath` variable for at all? Should we delete it entirely?

2023-04-25 02:54 UTC, defunctzombie commented on packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts
> -            newPath = `${path}[:]{${name}==${arrayElement[name]}}`;
There are two branches that set `newPath` to either `path[#]` or `path[:]`. No clear clue to me why since no tests fail. Maybe some storybook will fail.

2023-04-25 02:54 UTC, jtbandes commented on packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts
> -            newPath = `${path}[:]{${name}==${arrayElement[name]}}`;
With this change as-is, this comment would now be wrong: https://github.com/foxglove/studio/blob/5ab901d537b0a49425c0785ca46096ad3f58df39/packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts#L40

2023-04-25 04:21 UTC, defunctzombie commented on packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts
> -            newPath = `${path}[:]{${name}==${arrayElement[name]}}`;
Yea - the code has not made that a reality for a long time. I'll update the comment to strip away some of the incorrect statements.

2023-04-25 16:32 UTC, jtbandes commented on packages/studio-base/src/components/MessagePathSyntax/useCachedGetMessagePathDataItems.ts
> -            newPath = `${path}[:]{${name}==${arrayElement[name]}}`;
To provide a concrete example of where this code is used, if you have a Raw Message panel using a path with a `[:]` slice, and you click the button to open a corresponding plot panel, it will fill in the `id` as a filter when creating the plot panel.

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/14237/234340560-777f6627-260e-4ef3-b85a-a86621471e0a.png">

🤦  It also appears that the id is not properly quoted, since it should be `{id=="c08b"}` and not `{id==c08b}`. This seems to have been an oversight because it works fine for numeric ids, but not strings.

2023-04-25 16:34 UTC, jtbandes requested changes
We should either restore the functionality that was broken in #622, or delete the `newPath` stuff entirely. No reason to partially delete it when we know what the more correct code looked like and it would be easy to restore. (Or, at least, you have not provided a reason 😄)

To provide a concrete example of where this code is used, if you have a Raw Message panel using a path with a `[:]` slice, and you click the button to open a corresponding plot panel, it will fill in the `id` as a filter when creating the plot panel.

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/14237/234340560-777f6627-260e-4ef3-b85a-a86621471e0a.png">

🤦  It also appears that the id is not properly quoted, since it should be `{id=="c08b"}` and not `{id==c08b}`. This seems to have been an oversight because it works fine for numeric ids, but not strings.


This is where it was previously used in the plot tooltip, but we've deleted that code in Studio:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/14237/234343307-81e8b319-d1cf-4ea3-b1d4-3eab6d42b23f.png">

2023-04-25 16:47 UTC, defunctzombie commented
> To provide a concrete example of where this code is used, if you have a Raw Message panel using a path with a `[:]` slice, and you click the button to open a corresponding plot panel, it will fill in the `id` as a filter when creating the plot panel.

I find this behavior completely arbitrary. Maybe in practice it works perfectly? But right now with our current logic you get the `[#]` index of the array item you selected. If you want to change that as a user you can.

I am 👎 On putting back this feature given its been missing for two years and I've not heard one single request around it.

2023-04-25 20:00 UTC, jtbandes approved these changes

2023-05-10 00:54 UTC, jtbandes commented
Anything more that needs to be done here besides resolving the merge conflict?

2023-05-10 02:51 UTC, defunctzombie commented
I followed your example above and with this change the value on the plot panel is `/markers/annotations.entities[18].frame_locked` whereas before it would be `/markers/annotations.entities[:]{id==85d7}.frame_locked`. Notably as we learned, the latter does not work with string _id_ values.

I am inclined to merge the behavior we have in this PR and see what (if any) downstream impact there is. Our SceneEntity messages use a `string` id and the current behavior would not work for them. I can see a user being impacted by this and if that surfaces we can re-visit the behavior and add a test for it if we want to add it back for some set of fields.

2023-05-10 02:59 UTC, jtbandes approved these changes

2023-05-10 03:01 UTC, jtbandes commented
Still not sure what “downstream impact” we are looking for here — we know what the impact is, don’t we? Is the question whether any users will care?

2023-05-10 03:01 UTC, defunctzombie commented
> Is the question whether any users will care?

Yea - that's the downstream impact. Whether there are literally any users of this aspect of the raw message panel - which is the only place this surfaces.

2023-09-09 00:02 UTC, closed without merging