Use EmptyState for the empty states in the sidebar
foxglove/studio pull request #5914
Opened 2023-05-04 22:04 UTC by 2metres

**User-Facing Changes**
Make sidebar empty states consistent

2023-05-04 23:12 UTC, jtbandes commented
Topics empty state is still bold while the others aren't.

2023-05-05 04:40 UTC, 2metres commented
![image](https://user-images.githubusercontent.com/924528/236378890-998a704c-709d-4813-bdef-3483f6097d61.png)

2023-05-05 04:55 UTC, jtbandes requested changes
Not there yet. Topics empty state is still bold while the others aren't.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/14237/236380241-4e825573-dca1-4fae-b9c6-c99d2a355592.png">

<img width="323" alt="image" src="https://user-images.githubusercontent.com/14237/236380249-fd1ab012-1f98-49c2-af3a-00112aad0306.png">

<img width="325" alt="image" src="https://user-images.githubusercontent.com/14237/236380264-b00588b5-263e-4453-8c08-e21c6f39463c.png">

2023-05-05 05:00 UTC, jtbandes commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +        return "Loading topics";
Can we avoid changing the strings/logic in this PR? Off the top of my head I don't think BUFFERING should result in an EmptyState being shown, since it can happen even once topics are already known.

2023-05-05 05:08 UTC, 2metres commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +        return "Loading topics";
I think the current logic is wrong though. If you filter the text your end up with: 
<img width="313" alt="Screen Shot 2023-05-05 at 3 08 03 pm" src="https://user-images.githubusercontent.com/924528/236381426-843a78d4-2010-421e-aa06-8a4f3f16d0be.png">

2023-05-05 05:09 UTC, 2metres commented on packages/studio-base/src/components/DataSourceSidebar/TopicList.tsx
> +        return "Loading topics";
I can remove the BUFFERING string as it's not used

2023-05-05 16:57 UTC, jtbandes commented on packages/studio-base/src/panels/Image/components/ImageEmptyState.tsx
> +        Waiting for images{markerTopics.length > 0 && "and markers"} on:
😬 
```suggestion
        Waiting for images {markerTopics.length > 0 && "and markers"} on:
```

2023-05-05 16:58 UTC, jtbandes approved these changes

2023-05-05 17:12 UTC, jtbandes commented on packages/studio-base/src/components/EmptyState.tsx
> +    whiteSpace: "pre-wrap",
```suggestion
    whiteSpace: "pre-line",
```

2023-05-05 17:20 UTC, merged

2023-05-08 22:42 UTC, esthersweon commented
Also think the copy should be consistent across all states (all complete sentences with a period, or all phrases without a period).