Notify clients of UserProfileStorageContext on changes
foxglove/studio pull request #6032
Opened 2023-05-15 23:09 UTC by foxymiles

**User-Facing Changes**
None

**Description**
Invalidate the `getUserProfile` callback on `UserProfileStorageContext` so that clients know when the profile has been updated.

2023-05-15 23:35 UTC, 2metres approved these changes

2023-05-17 18:16 UTC, defunctzombie requested changes
The force dependency update is sign that the structure here is wrong.

2023-05-17 18:16 UTC, defunctzombie requested changes
The force dependency update is sign that the structure here is wrong.

2023-05-17 23:11 UTC, foxymiles commented
> The force dependency update is sign that the structure here is wrong.

Really the fix is to not make this async anymore. I'll handle that separately.

2023-05-17 23:11 UTC, closed without merging