Avoid showing the welcome dialog when using file -> open local file
foxglove/studio pull request #6078
Opened 2023-05-21 05:42 UTC by defunctzombie

**User-Facing Changes**
Fixes an issue where the user is first shown the welcome dialog when using File -> Open local file and then shown the file picker.

**Description**
Update the DataSourceDialog to hide itself when the active view is "file". This avoids showing the dialog when a user wants to select a file using the new app menu.

A quirk of the way we are leveraging the dialog for workspace actions is that if the user cancels the file picker they will be brought back to the welcome dialog.

2023-05-21 19:45 UTC, jtbandes reviewed
My general feeling is that triggering the open file action from the menu should not need to involve the OpenDialog. Adding extra code paths inside the dialog to support this while not actually rendering the dialog seems much more awkward than just adding a direct flow from menu item->show file picker->create player.

2023-05-21 19:56 UTC, defunctzombie commented
@jtbandes I agree. Did we overlook this insight when the workspace actions were added? That would have been the best time to address this nuance rather than end up in the current situation. The second best time is now.

2023-05-21 23:49 UTC, foxymiles commented
> @jtbandes I agree. Did we overlook this insight when the workspace actions were added? That would have been the best time to address this nuance rather than end up in the current situation. The second best time is now.

All the workspace actions did was hoist a few state variables from the `Workspace` component itself into the store. Nothing inside the business logic of the dialog itself was changed.

2023-05-22 00:28 UTC, foxymiles commented
We've had this quirk as far back at least as 1.40 before any of this stuff was in the workspace store. You can see if you use the file menu in the desktop app:

https://github.com/foxglove/studio/assets/93935560/a484cb7e-259e-46bb-8a8a-6aa52cfcff02

I agree with @jtbandes that the longer term fix is to move this logic out of the DataSourceDialog but as a workaround we could add another flag to the data source dialog store state to tell it it's being used in this way and not reappear when the file dialog is canceled.

2023-05-22 15:25 UTC, jtbandes commented
I think if we're looking to solve this problem now, there's no reason to go with a quicker workaround and I'd rather see us implement the desired solution, whatever it may be.

2023-05-22 21:38 UTC, jtbandes requested changes
see above

2023-05-23 04:18 UTC, foxymiles commented
Alternative solution: https://github.com/foxglove/studio/pull/6100

2023-05-23 23:26 UTC, defunctzombie commented
Closing in favor of alternatives. Agree that there's a better way to tackle this than this hack.

2023-05-23 23:26 UTC, closed without merging