2metres/app bar colors in theme
foxglove/studio pull request #6139
Opened 2023-05-29 00:20 UTC by 2metres

**User-Facing Changes**
None

**Description**
Moves AppBar constants into the theme

2023-05-30 17:19 UTC, jtbandes commented on packages/studio-desktop/src/main/StudioWindow.ts
> +const theme = palette[nativeTheme.shouldUseDarkColors ? "dark" : "light"];
I don't think this will work when toggling between dark and light mode, will it?

2023-06-01 00:19 UTC, 2metres commented on packages/studio-desktop/src/main/StudioWindow.ts
> +const theme = palette[nativeTheme.shouldUseDarkColors ? "dark" : "light"];
Appears to from local testing.

2023-06-06 00:28 UTC, jtbandes requested changes
main:

<img width="358" alt="image" src="https://github.com/foxglove/studio/assets/14237/4e2d105f-807b-486c-ab80-6d86d28d88db">
<img width="327" alt="image" src="https://github.com/foxglove/studio/assets/14237/7b03570b-98c0-4e92-a218-f899dd0ab881">


<br><br>
This branch:

<img width="291" alt="image" src="https://github.com/foxglove/studio/assets/14237/a218b054-7d04-4929-ae7a-ac3c65457742">

(icon color is wrong)

<img width="283" alt="image" src="https://github.com/foxglove/studio/assets/14237/0a71bc89-05f9-437e-891a-87ca2f541fc9">

(color does not change when toggling dark mode)

2023-06-06 02:36 UTC, 2metres commented
@jtbandes I couldn't get my Windows version running can you check to see if this is fixed by calling that theme in a different place?

2023-06-06 19:21 UTC, jtbandes commented on packages/studio-desktop/src/main/StudioWindow.ts
> +      browserWindow.setTitleBarOverlay(getTitleBarOverlayOptions({ isDark }));
Nope, still doesn't auto-adjust. This line looks wrong because isDark is not updated to the latest value.

Also, the icons are still black: 
<img width="162" alt="image" src="https://github.com/foxglove/studio/assets/14237/8b95c670-88d1-49b0-a975-01ac41475da8">

2023-06-14 00:31 UTC, 2metres commented on packages/studio-desktop/src/main/StudioWindow.ts
> +      browserWindow.setTitleBarOverlay(getTitleBarOverlayOptions({ isDark }));
Hmm… I'm out of my depth here. Could use some help causing it to re-render

2023-06-14 00:44 UTC, jtbandes commented on packages/studio-desktop/src/main/StudioWindow.ts
> +      browserWindow.setTitleBarOverlay(getTitleBarOverlayOptions({ isDark }));
Is there a ticket for this task? Maybe you can assign to me or if there isn't one, create one and assign me

2023-06-15 23:39 UTC, jtbandes approved these changes

2023-06-16 00:10 UTC, merged

2023-06-16 11:27 UTC, defunctzombie reviewed
nifty