Separate PanelList and PanelGrid for clarity
foxglove/studio pull request #6168
Opened 2023-06-01 06:04 UTC by 2metres

**User-Facing Changes**
None

**Description**
separation of styles and functionality

2023-06-01 06:23 UTC, 2metres commented on packages/studio-base/src/context/PanelCatalogContext.ts
> +
Not sure this is the right place for this but would like to put somewhere shared

2023-06-01 06:50 UTC, 2metres commented on packages/studio-base/src/components/PanelGrid/PanelGrid.tsx
> +  const noResults = allFilteredPanels.length === 0;
This code could all be potentially shared

2023-06-01 15:38 UTC, jtbandes requested changes
Separating these seems like a reasonable goal but there's a lot of duplicated logic right now. Maybe we need the boundaries to be a bit different where the search field and filtering logic is shared and only the rendering of the list/grid is not shared.

2023-06-02 19:44 UTC, jtbandes approved these changes

2023-06-06 02:27 UTC, merged