Moves publish panel inputs into panel settings
foxglove/studio pull request #6237
Opened 2023-06-13 03:22 UTC by 2metres

**User-Facing Changes**
<img width="902" alt="Screen Shot 2023-06-13 at 1 21 28 pm" src="https://github.com/foxglove/studio/assets/924528/8be9b708-a00a-4249-86ac-265f4d934aa7">

**Description**
Moves Topic and Schema inputs into panel settings and renames datatypes to message schema

2023-06-13 18:03 UTC, jtbandes commented on package.json
> +    "@storybook/csf-tools": "7.0.20",
what's this for?

> An experimental library to read, analyze, transform, and write CSF programmatically.

2023-06-13 18:03 UTC, jtbandes commented on packages/studio-base/src/panels/Publish/index.tsx
> -  // when a known topic is selected, also fill in its datatype
Was the deletion of this logic intentional?

2023-06-13 21:25 UTC, 2metres commented on package.json
> +    "@storybook/csf-tools": "7.0.20",
Attempting to debug the broken build, will remove now

2023-06-14 00:30 UTC, 2metres commented on packages/studio-base/src/panels/Publish/index.tsx
> -  // when a known topic is selected, also fill in its datatype
I think so. Now that we handle the topic selection in the panel settings we don't need to update the config from within panel

2023-06-14 01:26 UTC, jtbandes commented on packages/studio-base/src/panels/Publish/index.tsx
> -  // when a known topic is selected, also fill in its datatype
I think it would still be nice to auto select the schema when selecting a topic.

2023-06-14 01:26 UTC, jtbandes commented
I guess it's not new, but there's a strange height difference of autocomplete compared to other settings field types:

<img width="332" alt="image" src="https://github.com/foxglove/studio/assets/14237/513d0640-0f24-4b03-8f61-a7986f646798">

2023-06-14 01:41 UTC, jtbandes reviewed
Commented in Slack with some feedback

2023-06-14 03:41 UTC, 2metres commented on packages/studio-base/src/panels/Publish/index.tsx
> -  // when a known topic is selected, also fill in its datatype
I tried doing that in the panelSettings as well but caused a bug so removed it

2023-06-14 06:08 UTC, 2metres commented on packages/studio-base/src/panels/Publish/index.tsx
> -  // when a known topic is selected, also fill in its datatype
I've almost got it working where it auto selects the correct schema based on the Topic, Its currently off by one. I could use some immer help here

2023-06-15 12:10 UTC, defunctzombie commented
This PR is also changing the public extension api and something with the FieldEditor but does not call that out in the description. Could you elaborate on these changes since they become our public interface.

2023-06-15 19:41 UTC, jtbandes requested changes
Getting close. However the panel still crashes when I publish without a schema selected.

<img width="540" alt="image" src="https://github.com/foxglove/studio/assets/14237/9ef7fd24-cefb-453e-be1a-3622897321f3">

2023-06-15 19:41 UTC, jtbandes commented on packages/studio-base/src/panels/Publish/index.tsx
> +  usePublishPanelSettings(config, saveConfig, schemaNames, topics, datatypes);
seems like schemaNames is only used inside usePublishPanelSettings, it should move in there instead of being a parameter

2023-06-21 22:52 UTC, 2metres commented
@achim-k can you please test that this panel still publishes correctly?

2023-06-21 23:50 UTC, jtbandes approved these changes

2023-06-21 23:50 UTC, jtbandes commented on packages/studio-base/src/panels/Publish/settings.ts
> +        placeholder: "/some_topic",
I think this placeholder and `std_msgs/Type` below are sorta arbitrary and might be confusing to non-ROS users. Could just remove them and have no placeholder.

2023-06-22 01:41 UTC, merged