Re-process last active data when user scripts change
foxglove/studio pull request #6324
Opened 2023-06-28 22:23 UTC by defunctzombie

**User-Facing Changes**
When saving a user script, the updated script is run on its inputs to produce a new output message.

**Description**

2023-06-30 14:11 UTC, foxymiles commented
We recently added some code to emit new messages when the output topic list changes. Does this supersede that?

https://github.com/foxglove/studio/blob/e8b477e659a88763507abd929892915462ef47ef/packages/studio-base/src/players/UserNodePlayer/index.ts#L793-L813

2023-06-30 14:11 UTC, snosenzo requested changes

2023-06-30 14:11 UTC, snosenzo commented on packages/studio-base/src/players/UserNodePlayer/index.ts
> +            ...lastActive,
Currently we would re-emit all of the previous messages when we really only should re-emit computed messages. we should set `messages:[]` so that panels don't receive duplicates. Also we should update `_getMessages` to only return computed messages when recomputing. This should eliminate duplicate messages on original topics.

2023-06-30 16:56 UTC, defunctzombie commented
@snosenzo good insight. I've updated the PR to avoid re-emitting previous message data when re-computing. I've also removed the caching of the previous output since we target the invariant that we don't emit the _same_ `messages` into player state on emits. If we determine we need to guard against this we can do that better with a reference check or fix upstream.

I also updated tests which behave differently under the new changes so take a look at those.

2023-06-30 16:57 UTC, defunctzombie commented
> We recently added some code to emit new messages when the output topic list changes

Not entirely sure I follow. Are you thinking we can remove that code with these changes?

2023-07-06 14:08 UTC, snosenzo approved these changes
Looks good for the most part but, can you remove the empty emits in the node player tests that used to be there to emulate the idle emit?  for example:
<img width="484" alt="image" src="https://github.com/foxglove/studio/assets/10187776/0ba02654-542e-4d4b-b4b2-7ea0f48e7049">

2023-07-06 14:08 UTC, snosenzo commented on packages/studio-base/src/players/UserNodePlayer/index.ts
> +            messages: [],
nit: is it worth making this a stable constant array for referential equality and not having to instantiate a new array every time?

2023-07-06 14:42 UTC, defunctzombie commented on packages/studio-base/src/players/UserNodePlayer/index.ts
> +            messages: [],
I doubt this makes an impact given we are making new objects to host this array.

2023-07-06 15:06 UTC, merged