Expose foxglove schemas to user scripts
foxglove/studio pull request #6376
Opened 2023-07-06 15:49 UTC by foxymiles

**User-Facing Changes**
Expose foxglove schema definitions to user scripts.

**Description**
Expose foxglove schema definitions to user scripts.

I haven't been able to get this to work as `@foxglove/schemas` so it's `FoxgloveSchemas`.

2023-07-06 16:47 UTC, foxymiles commented
@esthersweon We should probably mention this in the docs.

2023-07-06 22:41 UTC, jtbandes commented on packages/studio-base/src/panels/NodePlayground/Editor.tsx
> +        }
Rather than `if/else` here, would it be more clear if we set the `fileName` to include the `@types/` for the other libs we generate?

2023-07-07 03:20 UTC, defunctzombie commented
> @esthersweon We should probably mention this in the docs.

Good opportunity to make a linear issue for this or next cycle so we don't forget :D

2023-07-07 03:22 UTC, defunctzombie commented on packages/studio-base/src/panels/NodePlayground/Editor.tsx
> +        // This is needed for @foxglove/schemas to resolve correctly in the editor.
Why?

2023-07-07 03:24 UTC, defunctzombie commented on packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/foxgloveSchemaDeclarations.ts
> +
Lets add a comment to this file letting us know its purpose. My guess is that this file provides the declarations for making the @foxglove/schemas import work?

2023-07-07 03:26 UTC, defunctzombie commented on packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/types.ts
> +export type NodeProjectFile = {
I know these didn't have comments before - but maybe you've learned their purpose and could help our future selves out by adding some learnings on how these connect into the larger user-script environment or config.

2023-07-07 03:40 UTC, defunctzombie reviewed
Good stuff.

How do we help users discover this? Does it make sense to update our default template (or other templates) to make this obvious for first time and repeat users? I'm imagining that its a reasonably common activity to use a user-script to output a well-known schema.

2023-07-07 13:12 UTC, foxymiles commented on packages/studio-base/src/panels/NodePlayground/Editor.tsx
> +        // This is needed for @foxglove/schemas to resolve correctly in the editor.
Not sure. Without this it seems to think `@foxglove/schemas/blah` is an alias.

2023-07-07 13:35 UTC, foxymiles commented on packages/studio-base/src/panels/NodePlayground/Editor.tsx
> +        }
Maybe although that would expand the scope of this PR a fair bit.

2023-07-07 13:37 UTC, foxymiles commented
> How do we help users discover this? Does it make sense to update our default template (or other templates) to make this obvious for first time and repeat users?

Not sure. I guess at least some of our templates could use this.

2023-07-07 17:16 UTC, defunctzombie commented
> Not sure. I guess at least some of our templates could use this.

What do we need to get sure? Something good to add as follow-up tickets if we don't want to do it with this PR but its important that we actually make this discoverable by more than word of mouth.

2023-07-07 17:20 UTC, defunctzombie commented
I tried the preview deployment and got this error with the nuscenes data:

<img width="826" alt="image" src="https://github.com/foxglove/studio/assets/84792/ac3f2684-33c8-497b-848a-972ff141e1c4">

```typescript
import { Input, Message } from "./types";
import { Log } from "@foxglove/schemas";

type Output = Log;

export const inputs = ["/gps"];
export const output = "/studio_script/output_topic";

export default function script(event: Input<"/gps">): Output {
  return {
    file: "",
    message: JSON.stringify(event.message),
    name: "",
    line: 0,
    level: 1,
    timestamp: event.receiveTime,
  };
}
```

Were you able to get user scripts to work with this deployment?

2023-07-07 18:10 UTC, foxymiles commented
> Were you able to get user scripts to work with this deployment?

I've tried with a bunch of types which all worked. There seems to be an issue specifically with `Log`.

2023-07-07 18:11 UTC, foxymiles commented
> > Not sure. I guess at least some of our templates could use this.
> 
> What do we need to get sure? Something good to add as follow-up tickets if we don't want to do it with this PR but its important that we actually make this discoverable by more than word of mouth.

Somebody needs to spend more time in the bowels of the Monaco typescript configuration.

2023-07-07 18:11 UTC, defunctzombie commented
> There seems to be an issue specifically with `Log`.

I'm gonna claim the QA of the month for this one.

2023-07-10 15:41 UTC, defunctzombie commented
@foxymiles I am still seeing the same error when trying to use `import { Log } from "@foxglove/schemas";` How were you able to get this to work?

2023-07-10 15:52 UTC, foxymiles commented
> @foxymiles I am still seeing the same error when trying to use `import { Log } from "@foxglove/schemas";` How were you able to get this to work?

No there's still an obscure error with Log. Every other type I've tried seems to work fine.

2023-07-10 15:55 UTC, defunctzombie requested changes
We need to resolved the error with using the `Log` schema.

2023-07-12 15:28 UTC, foxymiles commented
@defunctzombie This script with all types defined inline also generates the same error on main so I think we need to address this in the schemas package:

```typescript
import { Input, Message } from "./types";

type Time = {
  sec: number;
  nsec: number;
};

export enum LogLevel {
  UNKNOWN = 0,
  DEBUG = 1,
  INFO = 2,
  WARNING = 3,
  ERROR = 4,
  FATAL = 5,
}

type Log = {
  /** Timestamp of log message */
  timestamp: Time;

  /** Log level */
  level: LogLevel;

  /** Log message */
  message: string;

  /** Process or node name */
  name: string;

  /** Filename */
  file: string;

  /** Line number in the file */
  line: number;
};

type Output = {
  log: Log;
};

export const inputs = ["/gps"];
export const output = "/studio_script/output_topic";

export default function script(event: Input<"/gps">): Output {
  return {
    log: {
      file: "",
      message: JSON.stringify(event.message),
      name: "",
      line: 0,
      level: 1,
      timestamp: event.receiveTime,
    },
  };
}
```

2023-07-12 15:34 UTC, foxymiles commented
Perhaps related: https://github.com/cruise-automation/webviz/issues/613

2023-07-12 15:48 UTC, defunctzombie commented
@foxymiles When you open a data source that has a `foxglove.Log` message you can use `Message<"foxglove.Log">` and that works? What is different about the type we create from the data source schema? Is it the LogLevel type?

The issue you linked mentions union but that's not the same error here.

2023-07-12 15:52 UTC, foxymiles commented
> @foxymiles When you open a data source that has a `foxglove.Log` message you can use `Message<"foxglove.Log">` and that works? What is different about the type we create from the data source schema? Is it the LogLevel type?

Not sure but this is clearly an issue with our user script TS environment and not specific to our `@foxglove/schemas` integrtation and doesn't seem like something that should block this PR and keep this feature out of user's hands.

2023-07-12 15:52 UTC, foxymiles commented
@snosenzo did some good detective work on this in slack.

2023-07-12 15:58 UTC, foxymiles commented
I think we should open a ticket to track that something like this doesn't work today and generates the same error message:

```typescript
// The ./types module provides helper types for your Input events and messages.
import { Input, Message } from "./types";

enum MyEnum {
  A,
  B,
}

type Output = {
  hello: string;
  enum: MyEnum;
};

export const inputs = ["/imu"];

export const output = "/studio_script/output_topic";

export default function script(event: Input<"/imu">): Output {
  return {
    hello: "world!",
    enum: MyEnum.A,
  };
}
```

2023-07-12 23:14 UTC, jtbandes approved these changes
Do we need to think about what happens if a data source is loaded that uses a newer version of schemas? Will users be confused if the `@foxglove/schemas` import is out of date? Or maybe it will be clear that `@foxglove/schemas` comes from an embedded package and if you want to use your data source types, you import from the types lib.

What do you think it would take to get auto-import working? So e.g. if I start typing SceneEntity in my function, the editor would be able to add the import for me?

2023-07-12 23:14 UTC, jtbandes commented on packages/studio-base/src/panels/NodePlayground/Editor.tsx
> +        moduleResolution: ModuleResolutionKind.NodeNext as any,
why doesn't the moduleResolution param accept a ModuleResolutionKind? what does it accept and should we be using that type instead?

2023-07-14 05:17 UTC, jtbandes requested changes
I just realized another issue that needs to be addressed for this to work. Although we are able to generate "datatypes" from these imported schemas, the `schemaName` going downstream is currently wrong. Since there is no logic to associate an import from `@foxglove/schemas` with a particular `schemaName`, it is using the fallback path of generating a schema name from the user script name: 
<img width="978" alt="image" src="https://github.com/foxglove/studio/assets/14237/4435c7e5-b34c-42a1-842d-d7f3d0ce9a62">

In order for panels to be able to use the outputs of these scripts properly, the schemaName will need to be correct.

2023-07-14 12:16 UTC, foxymiles commented
> I just realized another issue that needs to be addressed for this to work. Although we are able to generate "datatypes" from these imported schemas, the `schemaName` going downstream is currently wrong.

Good observation. Do you think we should block this until we can find a solution? It's no worse than using a user-defined type in a script today right?

2023-07-14 13:45 UTC, defunctzombie commented
> Do you think we should block this until we can find a solution? It's no worse than using a user-defined type in a script today right?

Yes. We can't ship it without this because without the correct schema name the panels that work on schema name (3d, log, map) will not display the messages you produce. Think about how someone might want to use their scripts. Without this feature this script does not actually serve the intended purpose.

2023-07-14 14:57 UTC, snosenzo commented
> the schemaName going downstream is currently wrong.

We should definitely create a story to test this too with a userscript and raw message panel side-by-side

2023-07-14 15:53 UTC, jtbandes commented
We can test it with a unit test showing the extracted datatypes, doesn’t need to be a story.

2023-07-18 14:28 UTC, foxymiles commented on packages/studio-base/src/panels/NodePlayground/Editor.tsx
> +        moduleResolution: ModuleResolutionKind.NodeNext as any,
Seems like monaco is out of sync with typescript for this type.

2023-07-19 01:19 UTC, jtbandes approved these changes

2023-07-19 01:19 UTC, jtbandes commented on packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/transform.test.ts
> +          import { Color } from "@foxglove/schemas";
Include all the `generateFoxgloveSchemaDeclarations()` here so they're tested in the unit tests too and not just storybook?

2023-07-19 01:19 UTC, jtbandes commented on packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/projectConfig.ts
> + * Generates virtual ts files for each type exported by the @foxglobve/schemas package.
```suggestion
 * Generates virtual ts files for each type exported by the @foxglove/schemas package.
```

2023-07-19 04:03 UTC, defunctzombie approved these changes
Glad to see a bit of grit and teamwork got us to the result we wanted for this feature. Our users will be glad as well.

2023-07-19 07:20 UTC, jtbandes commented on packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/typescript/ast.ts
> +  const schemaName = match?.[1];
To be completely sure we can have a unit test for each of the foxglove schemas to ensure it can be correctly extracted if used as the return type of the function.

2023-07-19 11:49 UTC, foxymiles commented on packages/studio-base/src/players/UserNodePlayer/nodeTransformerWorker/transform.test.ts
> +          import { Color } from "@foxglove/schemas";
Since we're just doing a regex on the filename I don't think that would add much value and we'd have to write a structurally correct test for each type.

2023-07-19 12:01 UTC, merged