Add Font Settings for Raw Messages Panel
foxglove/studio pull request #6397
Opened 2023-07-07 06:10 UTC by turtle-operator

**User-Facing Changes**
- Add font setting for Raw Message panel
- Make single-value raw message display respect font setting

**Description**
Add option to overrule automatic large text display for primitive values in Raw Messages panel (as discussed in https://github.com/orgs/foxglove/discussions/618), as this takes a lot of screen real estate and might be counter-productive e.g. for long (multi-line) strings. For this, the font settings can be changed via the settings tree.

2023-07-07 06:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/foxglove/studio?pullRequest=6397) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/foxglove/studio?pullRequest=6397) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/foxglove/studio?pullRequest=6397) it.</sub>

2023-07-07 16:22 UTC, defunctzombie commented
Internal ticket: FG-4190

2023-08-01 15:11 UTC, defunctzombie commented
Could you remove the change for `Remove (maybe) collapsing values for single values.` to reduce the amount of things you are changing in one PR. We can focus this PR on adding font settings and respecting those font settings in the panel. Once that change is made we'll do a preview deployment on this PR and see how we like the UX.

2023-08-08 02:54 UTC, defunctzombie commented
@turtle-operator Is this PR ready for review or are you still working on the draft?

2023-08-08 06:19 UTC, 2metres requested changes

2023-08-08 06:19 UTC, 2metres commented on packages/studio-base/src/panels/RawMessages/types.ts
> +  FONT_SIZE_OPTIONS: [8, 9, 10, 10.5, 11, 12, 14, 18, 20, 22, 24, 28, 32],
I would suggest updating size values to be more consistent with typography metrics 
```suggestion
  FONT_SIZE_OPTIONS: [8, 9, 10, 11, 12, 14, 16, 18, 24, 30, 36, 48, 60, 72],
```

2023-08-08 06:19 UTC, 2metres commented on packages/studio-base/src/panels/RawMessages/types.ts
> +  FONT_WEIGHT_OPTIONS: ["bold"],
Similarly with font weights we should call out the options we actually [provide we from the webfont](https://github.com/foxglove/studio/blob/8d68c29419b4c4c0d3354037b0bd5110cf261f0c/packages/studio-base/src/styles/assets/inter.css#L29-L55) otherwise we'll just get the browser's faux bolding

| Friendly name | CSS font weight |
|---|---|
| Regular | 400 |
| Medium | 500 |
| SemiBold (could be simplified to Bold)   | 600 |

2023-08-08 06:19 UTC, 2metres commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +                })),
See comment [below](#diff-6dae59b1df06a111a3fdc2b0899401bcb9b1ce7402dea843240f35e0c312bc92R26)

2023-08-08 06:19 UTC, 2metres commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +            font_size: {
🍹 Nit: Elsewhere in the app we tend to use camelCase is used for setting field names.

2023-08-08 06:19 UTC, 2metres commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +            font_weight: {
Same feedback [as above](#diff-ca8a3a46914acc5156ff9c15ee6b85815754f4f4a02f2f2cd0e6d2c718cd2caaR640)

2023-08-09 13:34 UTC, snosenzo commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +              value: customFontWeight,
should we have default placeholder values for these?

2023-08-09 18:31 UTC, snosenzo commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +              value: customFontWeight,
Right now it shows this by default because this `value` field is `undefined`: 
<img width="324" alt="image" src="https://github.com/foxglove/studio/assets/10187776/a706629b-d774-44ed-9612-a3e18e018ffc">
By doing something like this:
```suggestion
              value: customFontWeight ?? (theme.typography.fontWeightRegular as number),
```
Doing this we can get rid of the red border and show what we use by default when `customFontWeight` (and `customFontSize`) are undefined.

2023-08-10 21:12 UTC, esthersweon commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +              label: "Font Weight",
```suggestion
              label: "Font weight",
```

2023-08-10 21:19 UTC, amacneil commented
Feedback from internal discussion:
- Need to remove indentation when viewing a single value
- Add `Auto` at top of font size dropdown which keeps current behavior (large font for single values), and remove `Default` label. When a font size is selected, it overrides the automatic behavior for both single values and trees. Justification: we don't have any other data points from users finding the current automatic behavior painful, so we don't want to break existing user workflows
- Remove `Font Weight` option and make it regular weight always (even when in auto mode) - keep things simple.

2023-08-11 18:27 UTC, defunctzombie approved these changes
LGTM! Thanks for going through the feedback and helping us polish the product.

Please sign the CLA and I'll be able to merge this.

2023-08-17 22:53 UTC, 2metres approved these changes

2023-08-18 18:45 UTC, jtbandes commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +                { label: "auto", value: undefined },
There are a few things about this that seem confusing to me.
- The "General > Font size" setting does not generally change the font size of the panel. It only changes it in the circumstance where you've drilled down to a single value — that seems like something we'd need to explain better in the UI, otherwise users will be confused when the dropdown doesn't do anything.
- There's nothing automatic about the "auto" setting — it just selects a particular size that happens to be inherited from the `h1` styling or something like that.
- The dropdown feels like it could be a numeric input field/slider? Not sure of the reasoning for using a dropdown.

We'll discuss these internally.

2023-08-18 20:44 UTC, jtbandes commented on packages/studio-base/src/panels/RawMessages/index.tsx
> +                { label: "auto", value: undefined },
Never mind, seems like I was mistaken! 🙌  Sorry about that

2023-08-18 20:45 UTC, merged