[Draft] Allow to skip messages in 3D/Image panel if possible
foxglove/studio pull request #6626
Opened 2023-08-10 21:23 UTC by achim-k

**User-Facing Changes**
Allow to skip messages in 3D/Image panel if possible

**Description**
Allows the 3D/Image scene extensions to decide if all messages have to be processed or if some messages can be skipped. Skipping messages will have positive impact on performance.

2023-08-11 14:07 UTC, snosenzo reviewed
Overall I think this approach looks good. Wish the `remainingMessagesOnSameTopic` was a little cleaner, but not a big deal. Also it should be straightforward for H264 to not have active. 
Would be good to add to other scene extensions as well

2023-08-11 14:07 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +    remainingMessagesOnSameTopic?: number,
This addition feels a bit awkward to me, but not sure what better way there would be. Maybe handling messages queues them, then another method flushes them to their handlers? Would be good to have a comment though because its usage is unclear

2023-08-14 13:46 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +  public handleCurrentFrameMessages(currentFrameMessages: readonly MessageEvent[]): void {
Comment for this function would be good

2023-08-14 13:47 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/Renderer.ts
> +  public addMessageEvent(
Should have comment describing parameters

2023-08-14 15:14 UTC, achim-k commented
> I have some small concerns about this being relatively hidden logic, and when debugging some folks might be wondering why some messages aren't being processed.

Do you think we should add a setting that lets users opt out of the skipping behavior if that causes problems?

2023-08-15 14:26 UTC, snosenzo requested changes

2023-08-15 14:26 UTC, snosenzo commented on packages/studio-base/src/panels/ThreeDeeRender/renderables/PointClouds.ts
> +            this.userData.settings?.decayTime != undefined &&
I don't think the scene extension uses `this.userData` only the `renderables`. For these (Point clouds and laser scans) I think you'll need to do something more complex. You'll need to use the topic to get the renderable and check the `.settings.decayTime` on the renderable

2023-08-16 09:57 UTC, KerstinKeller commented
I appreciate that you are tackeling this issue, as it is really blocking us 👍 And happy to test out the changes.

I understand too little about the Foxglove architecture, to really make informed comments here.
However, to me, the current realization by providing a bool if you may / may not skip a data element if a newer one is already in the queue feels a bit unintuitive.

When we designed plugins (for algorithms, or monitoring solutions) in the past that handle visualization, not the data callbacks triggered preparing the data for rendering, but rather rendering triggers did.
Depending on what you wanted to render (or compute for that matter), you would create a queue of the data you had received, or you would keep just the last message.
Then only during cyclic compute/rendering calls you would identifiy which was the correct data to be used for computations / drawn into the scene.

2023-08-21 16:45 UTC, achim-k commented
The following screencast shows a comparison between current Studio (left) and Studio as of https://github.com/foxglove/studio/pull/6626 (right):

[Screencast from 21.08.2023 13:36:39.webm](https://github.com/foxglove/studio/assets/9250155/1a44cc13-6faf-4d82-a8ca-8d7b790572b1)

Oberservations:
- Raw message panel shows latest message and immediately stops when the image publisher is stopped (left and right)
- The image panel on the right side is up to date whereas the left side is lagging behind
- When the image publisher is stopped, the left side keeps on rendering buffered messages

2023-11-16 14:50 UTC, achim-k commented
Closing this PR, superseded by https://github.com/foxglove/studio/pull/7064

2023-11-16 14:50 UTC, closed without merging