Show alert when marketplace extension fetch fails
foxglove/studio pull request #6635
Opened 2023-08-14 17:59 UTC by foxymiles

**User-Facing Changes**
None

**Description**
When the marketplace extension fails show an error alert and render the local extensions instead of rendering only the error message and leaving the rest of the view unusable.

<img width="726" alt="Screenshot 2023-08-14 at 11 59 05 AM" src="https://github.com/foxglove/studio/assets/93935560/3f1ae560-a137-4313-8514-d15bba5ca25c">

2023-08-15 23:29 UTC, jtbandes approved these changes
Would be nice to find a better design than just centering stuff, but I see that's existing code just being moved in this PR

2023-08-16 00:33 UTC, 2metres commented on packages/studio-base/src/components/ExtensionsSettings/index.tsx
> +        </Alert>
Use the Alert's `onClose` prop? https://mui.com/material-ui/react-alert/#actions

2023-08-16 00:36 UTC, 2metres commented on packages/studio-base/src/components/ExtensionsSettings/index.tsx
> +            </Typography>
Use the AlertTitle component
```suggestion
            <AlertTitle>Failed to fetch the list of available marketplace extensions,</AlertTitle>
            Check your Internet connection and try again.
```

2023-08-16 00:39 UTC, 2metres requested changes
Looks much better overall. Let's lean into the MUI alert a bit more

2023-08-16 00:39 UTC, 2metres commented on packages/studio-base/src/components/ExtensionsSettings/index.tsx
> +            </Button>
Use the Alert's `action` or `onClose` prop? https://mui.com/material-ui/react-alert/#actions

2023-08-16 00:39 UTC, 2metres commented on packages/studio-base/src/components/ExtensionsSettings/index.tsx
> +  Alert,
```suggestion
  Alert,
  AlertTitle,
```

2023-08-17 21:37 UTC, 2metres approved these changes

2023-08-17 23:26 UTC, merged