Add panel to call services
foxglove/studio pull request #6669
Opened 2023-08-18 19:23 UTC by achim-k

**User-Facing Changes**
Add panel to call services

**Description**
Adds a panel to call services (if the data source supports it). Look and feel is similar to the publish panel (code is based that one).

2023-08-21 22:33 UTC, jtbandes requested changes
We should structure the panel as an extension panel, using PanelExtensionAdapter. Then you can use the panel extension API to implement the settings, instead of `usePanelSettingsTreeUpdate`.

2023-08-21 22:33 UTC, jtbandes commented on packages/studio-base/src/panels/CallService/index.tsx
> +      error = "Message content must be an object, not an array";
nit: all these "Message content" might want to rename them to "Request content"?

2023-08-21 22:33 UTC, jtbandes commented on packages/studio-base/src/panels/CallService/settings.ts
> +import buildSampleMessage from "@foxglove/studio-base/panels/Publish/buildSampleMessage";
let's avoid importing from the Publish panel – we can move this function to some common/shared location

2023-08-21 22:33 UTC, jtbandes commented on packages/studio-base/src/panels/CallService/settings.ts
> +          { label: "horizontal", value: "horizontal" },
```suggestion
          { label: "Vertical", value: "vertical" },
          { label: "Horizontal", value: "horizontal" },
```

2023-08-21 22:33 UTC, jtbandes commented on packages/studio-base/src/panels/CallService/settings.ts
> +        label: "Service",
Maybe "Service name"?

2023-08-21 22:33 UTC, jtbandes commented on packages/studio-base/src/panels/CallService/types.ts
> +  datatype?: string;
let's use `schemaName` or `requestSchemaName` or something like that

2023-08-24 01:00 UTC, jtbandes commented on packages/studio-base/src/panels/CallService/CallService.tsx
> +      config.serviceName === "" ? undefined : `Call service ${config.serviceName}`,
Want to avoid "Call service undefined":
<img width="167" alt="image" src="https://github.com/foxglove/studio/assets/14237/7252a85c-b9a3-4c24-9c28-24238e764153">

```suggestion
      config.serviceName ? `Call service ${config.serviceName}` : undefined,
```

2023-08-24 21:57 UTC, jtbandes commented on packages/studio-base/src/panels/index.ts
> +    thumbnail: publishThumbnail,
I think it's ok to reuse the same one since the panels are similar. @2metres is the one who created the others

2023-08-28 18:27 UTC, achim-k commented on packages/studio-base/src/panels/index.ts
> +    thumbnail: publishThumbnail,
@2metres, we decided to merge this PR as is with the publish thumbnail. Feel free to open a follow-up PR that adjusts the thumbnail

2023-08-28 18:27 UTC, merged